### ISSUE TITLE
[Bug] Hardware wallet account name not reflecting on signing transaction screen

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#10079]
1. Connect QR/Ledger device on Metamask Mobile
2. Go to test dapp
3. Connect using hd wallet
4. Personal sign using hd wallet
5. Verify the sign transaction page displays

Expected: Hardware wallet account name to reflect with account list from homepage
Actual: Hardware wallet account name does not reflect

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3lIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe1260a3d717217e0bde65a52bd2e55527012d3c/RPReplay_Final1719230238.MP4)

Device: iPhone 13
OS: iOS 17.5.1
MM Version: 7.26.0 RC1 (1352)

**Comment by dawnseeker8** [comment]
hi, the issue was caused by PreferenceController and AccountController state(regarding the account name) is difference. and this PR @owencraston create should be able to fix the issue https://github.com/MetaMask/metamask-mobile/pull/9724

once above PR merged, we will redo a tests again to make sure the above PR will address the issue.

**Comment by bschorchit** [comment]
@vivek-consensys @dawnseeker8 do you if the mentioned PR should also fix this issue https://github.com/MetaMask/metamask-mobile/issues/10161 ?

**Comment by vivek-consensys** [comment]
@bschorchit yes, the issue mentioned should also be fixed with the PR.

**Comment by owencraston** [comment]
fixed by: https://github.com/MetaMask/metamask-mobile/pull/9724
