### ISSUE TITLE
[Bug]: Account token list is wiped out after upgrade and app restarts

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#10124]
### Describe the bug

After upgrading to 7.26.0 RC2 the account token list is wiped out, no longer showing the tokens for the account after upgrade.

Workaround is to reimport using token detection link.

### Expected behavior

Wallet configuration such as accounts, networks and tokens should properly persist after upgrade.

### Screenshots/Recordings

Before upgrade: 

https://github.com/MetaMask/metamask-mobile/assets/6626407/5ddfaf81-a7e8-4c4d-9e9e-307beb284d6c

After upgrade: 

https://github.com/MetaMask/metamask-mobile/assets/6626407/36092f29-f646-4228-a6b5-b9ae49bf3498

### Steps to reproduce

GIVEN I have tokens displayed for wallet accounts
WHEN I upgrade
THEN tokens displayed persist after upgrade (FAIL: tokens are no longer displayed)

### Version

7.26.0

### Build type

None

### Device

iOS and android

### Operating system

iOS, Android

**Comment by sahar-fehri** [comment]
Hey @chrisleewilcox  👋 , I think this bug is similar to [another](https://github.com/MetaMask/metamask-mobile/issues/10057) one related to NFT state being reset, but there is a fix that was already [submitted](https://github.com/MetaMask/metamask-mobile/pull/10133/files),

I was able to reproduce this behavior without the fix on the branch `release/7.26.0`, but with the fix, the upgrade works fine and i can see my imported tokens!

Is it possible that when reporting this issue, it was not on the latest version of the branch release/7.26.0?

**Comment by chrisleewilcox** [comment]
Hi @sahar-fehri.  Retested this on simulator with the latest on release branch and was not able to repro.  Will test again in the next RC and will close.

**Comment by chrisleewilcox** [comment]
Fixed by #10171
