### ISSUE TITLE
Support bip 0021 bitcoin style payment URI Requests for Ecommerce Payments

### ISSUE THREAD

**Issue by juscamarena** [MetaMask/metamask-mobile#1018]
ethereum:0x6c5916DA647a6076e38Cd9fd95d6f6a0046eCe12?amount=0.108245

Unit in ETH.

We want to support the web3 style QR encoded requests but other wallets already have the support for the above and has been in use for all other cryptocurrencies at least what we support for bitrefill.com, and seems we can't do both this uri support and web3 style ones for backward compatibility.

Any chance to support the above as well?

BRD is a wallet that already supports these kinds of request.

**Comment by brunobar79** [comment]
Hi @juscamarena 

We are already supporting [EIP-681](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md) including QR Codes.

Please note that the URL that you share it's not EIP-681 compatible since you're not using the scientific notation. 

The correct URL is ethereum:0x6c5916DA647a6076e38Cd9fd95d6f6a0046eCe12?amount=0.108245e17

And as you can see here it's already working: https://recordit.co/vs3UoFM5Qe

You can use this tool to generate valid payment links:  https://brunobar79.github.io/eip681-link-generator/#
