### ISSUE TITLE
Use amount given in QR codes

### ISSUE THREAD

**Issue by mmhh1910** [MetaMask/metamask-mobile#1152]
When a QR code with e.g. the content

ethereum:0x168444b211173cbec0bdc52e638a1b885762576b?amount=1.901

is scanned, only the address is used in the "Send" form, but the amount in the form is still zero.

**Comment by brunobar79** [comment]
Hi there,

That url is not formed correctly. 

Based on EIP-681 the format should be `ethereum: 0x168444b211173cbec0bdc52e638a1b885762576b?value=1.901e18` 

So instead of `amount`, the parameter name should be `value` and it should be expressed in scientific notation.

For more info check out this:  https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md
