### ISSUE TITLE
"Authentication required" on Android

### ISSUE THREAD

**Issue by john-light** [MetaMask/metamask-mobile#1177]
I had created and used MetaMask on an Android phone as recently as early October without having to go through the "Authentication Required" screen. However now when I enter the password to the wallet, I am prompted to "Please authenticate in order to use MetaMask".

I don't know what it's expecting me to do here since I have already entered my password. Whatever it is, I don't want to do it. I just want to use the wallet.

**Comment by brunobar79** [comment]
@john-light  Did you change any security settings in your phone? Enabled fingerprint, PIN, or something like that lately? or maybe upgraded your OS?

That's the (not very descriptive 😅 ) message that you get when the app is attempting to access the keychain. In your case it's probably trying to store your password for future authentication based on your device's settings.

Can you please check if in the screen where you enter your password do you have a switch at the bottom, and what does it say?

**Comment by john-light** [comment]
@brunobar79 there is a switch, it says "remember me" and it is enabled.

**Comment by brunobar79** [comment]
That makes sense. We're trying to store your password in the keychain due to the "remember me" option so you don't have to enter it in the future. 

We should improve that message ASAP.

Additionally, I think there's a bug where the "Pattern" lock  is not recognized as a security method enabled in the device, so we should also fix that or at least ask you if you want to create a 4 digit PIN.

**Comment by john-light** [comment]
@brunobar79 is it necessary to require authentication to do this (not require entering the password every time the app is opened)? Personally I prefer granting as little access to apps as possible and entering my PIN into an app screen feels weird (MetaMask is the only app that's every asked me to do that).

**Comment by brunobar79** [comment]
I hear you... The reason the app requires you to enter your password because it needs it to decrypt your wallet.  

On a separate note, the Lock Screen, which is what you see when you return to the app after having it on the background, it’s an optional security layer (enabled by default) and it can be disabled by going to settings =>  security & privacy => auto-lock => never

If you do that way you’ll be asked to enter your password only when you launch the app, not when you return to it but be aware that if someone gets  physical access to your phone unlicked your funds are at risk.

In the future, we might add an optional extra auth check (Fingerprint, faceID, PIN)  before sending transactions which should
mitigate that risk.
