### ISSUE TITLE
[Bug]: Token added to wallet after tapping send token deeplink, app crash on Token Details

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#11984]
### Describe the bug

After tapping a send token deeplink and cancelling the send on Confirm screen the token to send is added to wallet account and displayed on token list.  Tokens that are auto-added by a deeplink will crash app on Token Details view, even if the Token was already imported before tapping deeplink.

Send token deeplink: https://metamask.app.link/send/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48@1/transfer?address=0x2990079bcdEe240329a520d2444386FC119da21a&uint256=2.5e7

### Token auto-added to Token list after tapping send deeplink and cancelling send
- I think this an existing issue but app doesn't crash viewing Token Details on current production 7.33.0
- App is crashing viewing Token Details for this release 7.34.0

### Expected behavior

The app should not crash.

7.33.0

https://github.com/user-attachments/assets/f49787e0-e20e-4c32-b1ef-d9ae9485f85c

### Screenshots/Recordings

7.34.0
https://github.com/user-attachments/assets/feae9ac3-ec84-4dd6-8d93-ccd69a83c02a

### Steps to reproduce

GIVEN I tapped on a send token deeplink
AND wallet account does not have send token imported
AND send token Confirm screen is displayed
WHEN I tap 'Cancel'
THEN Confirm screen is dismissed
AND no transaction was executed
AND send token is not displayed on Token List (FAILED: token is added)

### Detection stage

During release testing

### Version

7.34.0

### Build type

None

### Device

Any

### Operating system

iOS, Android

**Comment by hesterbruikman** [comment]
On the Expected behavior
> Tokens should not be auto-added if send was cancelled.

I think it's fine if the token was added after using a 'Send token' deeplink. The user may or may not have balance for the token, but I don't think it's an issue for the token to be added to a list via a deeplink generally.

Expected behavior rather seems: "App does not crash when tapping on token, after respective token was used in a send deeplink".

@chrisleewilcox do you see any potential funds loss resulting from the crash? While not unlikely, I don't expect this to be a common scenario. In terms of reach, I don't consider it a `sev1` and I'm doubtful about the crash alone being a sev 1 if it's quick to recover. Not pretty, but I'm not sure it's worth holding up the release.

**Comment by salimtb** [comment]
cherry pick PR [link](https://github.com/MetaMask/metamask-mobile/pull/12065)
