### ISSUE TITLE
[Bug]: MetaMask app quits if dApp initiated transaction is rejected

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-mobile#12240]
### Describe the bug

DApp-initiated transactions can be confirmed successfully. However, every time when a transaction is rejected, the app unexpectedly quits. After quit the performance seems to be degraded.

Observed on Android devices only.

### Expected behavior

-

### Screenshots/Recordings

7.34.0 (1475):

https://github.com/user-attachments/assets/9a20f803-3f50-4334-b68c-f21ca98891cb

7.34.1 (1480):

https://github.com/user-attachments/assets/3ec944f1-f3f2-4510-b375-5f9b68bfe561

<img width="595" alt="Screenshot 2024-11-07 at 22 46 50" src="https://github.com/user-attachments/assets/8a632fdd-4fa8-420d-a4e1-d7ab790fac5f">

### Steps to reproduce

1. Connect to a dApp
2. Start transaction
3. Reject on Confirmation screen

### Detection stage

During release testing

### Version

7.34.0 (1475), 7.34.1 (1480)

### Build type

None

### Device

Samsung S24+

### Operating system

Android

**Comment by Emmaward090** [comment]
> ### Describe the bug
> DApp-initiated transactions can be confirmed successfully. However, every time when a transaction is rejected, the app unexpectedly quits.
> 
> Observed on Android devices only.
> 
> ### Expected behavior
> 
> ### Screenshots/Recordings
>  reject.mov 
> 
> <img alt="Screenshot 2024-11-07 at 22 46 50" width="595" src="https://private-user-images.githubusercontent.com/104780023/384219163-8a632fdd-4fa8-420d-a4e1-d7ab790fac5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzg4NjcsIm5iZiI6MTczMTAzODU2NywicGF0aCI6Ii8xMDQ3ODAwMjMvMzg0MjE5MTYzLThhNjMyZmRkLTRmYTgtNDIwZC1hNGUxLWQ3YWI3OTBmYWM1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwNDAyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjE1NmU1NWM3NGNjMmJiZjQ4YTEyZGU1YjIyYTg0MGFkOWRlN2I1MTI2NWMwN2UwNTM2NjQyNmQ4NTFhOTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.W0Qfh67u0kCNlINLykf5-1c3upXPoXatSBo8NFIrPbs">
> ### Steps to reproduce
> 1. Connect to a dApp
> 2. Start transaction
> 3. Reject on Confirmation screen
> 
> ### Error messages or log output
> _No response_
> 
> ### Detection stage
> During release testing
> 
> ### Version
> 7.34.0 (1475)
> 
> ### Build type
> None
> 
> ### Device
> Samsung S24+
> 
> ### Operating system
> Android
> 
> ### Additional context
> _No response_
> 
> ### Severity
> _No response_

It sounds like you're encountering a frustrating issue with your DApp. When a transaction is rejected and the app quits unexpectedly, it could be due to a few reasons.
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET09251
[Metamask support Network](http://Dextoolshub.com)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
@sleepytanya

**Comment by pedronfigueiredo** [comment]
No errors on the application code should cause the whole app to crash. If we pinpoint where the error is happening, the confirmations team can work on handling it, but it still would be preferable to address the underlying problem of crashing the UI separately.

**Comment by Cal-L** [comment]
@pedronfigueiredo  It is unclear what the culprit of the crash is at the moment until some debugging is done. Based on the description atm, the assumption is that the error is either related confirmations UI and/or other logic under the hood, which is why it was assigned to confirmations team. I can see that @sleepytanya Referenced https://github.com/MetaMask/metamask-mobile/pull/12228. @sleepytanya Since it's referenced, could you confirm if that fixed this issue? If not, could you assist in identifying the crash message? A simple way to do this is to connect your physical device and open Android studio. Once you run MM, the application should appear as an option in the Logcat, which will spew out logs including the error that occurs when it crashes. Feel free to reach out if you're having issues.

**Comment by sethkfman** [comment]
This issue seems related to the crash we are seeing in production #12266

**Comment by sleepytanya** [comment]
@Cal-L @sethkfman 
The bug is present in[ latest `main` build](https://app.bitrise.io/app/be69d4368ee7e86d/installable-artifacts/8ea190215436d184) meaning that https://github.com/MetaMask/metamask-mobile/pull/12228 didn't fix it.


https://github.com/user-attachments/assets/fb5d2a5c-044c-4384-a2c6-f2d0579b5ad5

**Comment by sleepytanya** [comment]
[logcat.log](https://github.com/user-attachments/files/17760320/logcat.log)
