### ISSUE TITLE
Dapp not working

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/metamask-mobile#1269]
From support ticket: http://gopherswild.com/vpp/

**Comment by woodydeck** [comment]
This is my highly centralized application. If it is not available it means I am working on it, or sleeping and the server crashed.  I would have bitched directly here had I known there was a mobile project branch that was public. 

Please note that I believe that there is a huge project disconnect currently where developers like me can get their information on MetaMask. Gitter isn't monitored, and I blew my top there as well as to support email. I'm very frustrated because I feel like this whole disconnect I'm experience is a major problem with crypto and decentralization in general.

I asked this related issue core to the functionality of MetaMask in dapps, but nobody officially answered:
https://ethereum.stackexchange.com/questions/78660/how-can-you-find-the-ethereum-provider-on-web3-browsers-other-than-metamask

I blame the Web3.js project as well. They have created three incompatible versions when there only need to be two, and then everyone downstream can't agree on how to implement things. I have no idea anymore what is 0.2, 1.2, or 2.0. I just want my users to be able to sign a message on mobile and on the desktop with an address (account) that is secured by a multi-billion dollar blockchain.

**Comment by rdymac** [comment]
On Mobile this dapp/website: dice2.win , is supposed to ask the user for approval, but instead it goes directly to rejected without showing the user any MetaMask prompt.

Case: 29772

**Comment by woodydeck** [comment]
I have given up the fight, and have returned to centralized projects. I am very disappointed this was not prioritized. My project is not viable without a working web3 wallet on mobile. I am still available for help, but I can't guarantee my test server will stay live.

Funnily enough, I got things to work with Tron. All of the core Ethereum devs like to take shots at Tron, but fact is that they are currently more advanced than Ethereum's primary chain. 

After the last 24 hours and seeing the Iowa Caucuses turn into a shitshow it is clear how important blockchain is in conjunction with centralized ad hoc services. Results can be public, and authentication can be much more secure than the passwords they emailed (!) to precinct managers.

**Comment by rekmarks** [comment]
@woodydeck I apologize it has taken us so long to get back to you. We are a small team, and unfortunately have triage based on project size.

Your dapp seems to be working in our mobile app now, using the latest `develop`. It should be on TestFlight for iOS soon if it isn't already. Our Android releases are held up at the moment.

I think that you are handling the `accountsChanged` event incorrectly, but I was able to log in and hit `Deal` just now. I'm not sure how it's supposed to work, so I can't be sure. See image below.

I'm happy to help if you have further questions! Otherwise I will close this issue in one week from today.

![image](https://user-images.githubusercontent.com/25517051/74268138-31b92000-4cbc-11ea-8d97-fd10fc266b76.png)

**Comment by rekmarks** [comment]
@rdymac I just went to dice2.win on latest `develop` and it asked me to connect. We've updated the provider so it may be due to that.

**Comment by woodydeck** [comment]
> I apologize it has taken us so long to get back to you. We are a small team, and unfortunately have triage based on project size.

This issue should be #1. People actually were interested in vesting hundreds of thousands to develop similar games until I advised of the bottleneck. They won't be back for many years to explore this now unfortunately and I have moved on to mundane centralized stuff again.

I also think evangelists should be promoting this centralized approach as a stop gap so we get adoption. The blockchain is slow, expensive, bloated, and Web3 is a mess now. MetaMask doesn't have to be a mess as long as this flow is unimpacted.

>I think that you are handling the accountsChanged event incorrectly, but I was able to log in and hit Deal just now. I'm not sure how it's supposed to work, so I can't be sure. See image below.

It's copy pasta from the docs besides what Phaser does when it happens. I'm curious to exactly what you mean?

The program has to log you out when you change accounts because the websocket authentication decodes a JWT that has an address embedded. You could issue a new token with the new address if this happens, but this raises security issues with spoofing, so it's best to just have them take two clicks to sign another nonce. Also, gaming regulations can require affirmative consent, and login logs, though that wasn't the primary reason.

If you want the source code, I can send to you privately.

**Comment by rdymac** [comment]
> @rdymac I just went to dice2.win on latest `develop` and it asked me to connect. We've updated the provider so it may be due to that.

So it should work once `develop` has been merged to `master` and a new version is published, right?

<br />

New report of a dapp not working on MetaMask Mobile. Case number: 31236

_Mobile Browser not executing get calls_
_Our DApp, Cryptomibs, has been working fine with your mobile [app] up until a few days ago. Now your [mobile app] is not executing get calls form DApp. We have no issues with regular mobile browsers. We really need your help to get this resolved. Thank you._

**Comment by woodydeck** [comment]
It doesn't work yet on the test flight version v0.2.13 build 356.

I was spending some time getting orientation hack to work by sniffing user agents. I am not sure if there is a separate issue for that. The lack of orientation is a bummer for games.
