### ISSUE TITLE
Unable to click submit on bug report or support ticket page on android devices

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1295]
User reported being unable to submit a ticket directly within the app.  One of our CS agents was able to reproduce this on his Android device: https://imgur.com/B5NgwOS

Re: support case: 29719

**Comment by rickycodes** [comment]
i can take a look at this one later today/early tomorrow

**Comment by rickycodes** [comment]
@dpazdan actually looking at the imgur link it seems like maybe all they just needed to use the re-captcha? regardless that submit should maybe be inactive until the form is ready. I'll confirm what's up when I can tether my device.

**Comment by georgeandrei** [comment]
@rickycodes wouldn't the re-captcha pop up after clicking on submit? Also, i have another user that faces some challenges with the re-captcha on android, in a different situation (setting up an account with a dapp, no re-captcha pop-uo)

**Comment by rickycodes** [comment]
yea, I've reproduced the issue and can confirm it has nothing to do with the re-captcha. For whatever reason it appears we're blocking whatever is supposed to happen when you click submit. I've compared things to what happens when you go to the form directly in a browser (which appears to be fine). maybe instead of going to a webview we should just launch the forms in a separate browser window to get this closed?
