### ISSUE TITLE
Payment request doesn't show other asset options

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1445]
**Describe the bug**
Payment request doesn't show other assets than ETH

**Screenshots**
<img src="https://user-images.githubusercontent.com/44038140/77217178-a8c4ae00-6add-11ea-93df-d352a9149332.png" width="200" height="350">

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to 'Receive'
2. Click on 'Request'
3. Asset selection options don't show options other than ETH

**Expected behavior**
Show: Search bar, Top picks, Your tokens

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8+]
 - Version 0.2.14

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by andrepimenta** [comment]
The "Search bar, Top picks, Your tokens" appear only when the mainnet is selected:
![image](https://user-images.githubusercontent.com/4960833/78401987-c1f74f80-75f1-11ea-9bc6-3df84bc0e076.png)

The Search bar does not appear on testnets because we don’t maintain a list of tokens for networks other than the mainnet for now. So only the Top picks and Your tokens will appear:
![image](https://user-images.githubusercontent.com/4960833/78402169-0be03580-75f2-11ea-8406-30cc87516f78.png)
