### ISSUE TITLE
Default landing page where user left off

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#1535]
**Describe the usability problem**
When user opens the app, right now we load the Browser view, which opens the last dapp user was on. This gives a lack of context to user. Plus the dapp loading typically is slow - this leads to bad UX.

**Expected behavior**
Let's either
- load the view that user was active on before they killed the app
- ask them if they want to open on Wallet or Browser (homepage) - optionally give option to save this preference (and later change in setting)
- load the browser homepage

@cjeria what's your advise here?

**Comment by cjeria** [comment]
Of the suggested behaviors, what makes the most sense to me is 

> • load the view that user was active on before they killed the app

Ideally, we would adapt to users' behaviors. For e.g. if a user spends more time on the wallet view, load the wallet view, and vice-versa. Since introducing Ai isn't feasible today, the fallback is to load the last view the user was on, even if they have restarted the app and device (assuming this is possible?)
