### ISSUE TITLE
Trouble with deep links

### ISSUE THREAD

**Issue by Gropher** [MetaMask/metamask-mobile#1596]
**Describe the bug**
I'm trying to use deep link to get the result of transaction back into my native Android app but it doesn't work. 
I'm getting ERR_UNKNOWN_URL_SCHEME error after redirect to my app link: jjoapp://open?click_id=123456

**Screenshots**
https://ibb.co/Bq5WRhY

**To Reproduce**
Redirect to any deep link in Metamask browser

**Expected behavior**
After redirect to deep link Metamask opens the app in question

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi-4c
 - OS: MIUI 10 8.9.13 beta, Android 7.0
 - Version v0.2.16 (29)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by omnat** [comment]
Hi @Gropher, I can't reproduce this issue with [MetaMask deeplinks](https://metamask.github.io/metamask-deeplinks/#).

Can you give more context into what you are trying to achieve?

1. Are you creating a deep link transaction from within another app, and then have their users redirected back to that app?
2. Which deeplink are you using? 
3. Do you support Wallet Connect?

**Comment by Gropher** [comment]
1. Our android app passes method and params for ethereum.sendAsync to the backend and get metamask deep link like this: https://metamask.app.link/dapp/jjo.dev1.idfly.ru/api/v2/metamask/c4a9a8c5-c3c9-4937-9ef4-30735f115423
2. Then the app redirects user to this link, metamask opens, ethereum.sendAsync being executed with requested params 
3. Then we need to pass the result of ethereum.sendAsync call back into the app, so we use https://branch.io to create deep link into our app with result encoded in it: jjoapp://open?click_id=123456

This whole procedure works fine on iOS but on Android we getting ERR_UNKNOWN_URL_SCHEME error on final step

**Comment by RoyalSix** [comment]
@Gropher You are saying you were able to open another from from within the MetaMask Browser? How did you achieve this?
I am trying to use deep linking but its not working for me.

For example after the user is finished interacting on MetaMask and its time for them to go back to "MyApp" I do 
```js
window.location.href = "myapp://user?id=12345"
```

but nothing happens. Are you able to expand more on this? Or do can you explain your implementation using `branch.io`

Thank you!

**Comment by Thaina** [comment]
I too have a problem open firebase dynamic link or any deep link in metamask

![image](https://user-images.githubusercontent.com/1042507/151345167-6871991a-6184-42da-ba52-d948f9658c29.png)

Even the firebase dynamic link actually use `intent://` url scheme so it become broken when metamask cannot handle it. This very much decrease metamask app usability for other dapp

I think the solution is that metamask should at least open any error link in the external browser, or relegate them to native OS to handle instead of this useless `ERR_UNKNOWN_URL_SCHEME` message

And there was a fix at least for `intent://` schema that firebase was used with `originWhitelist` attribute and `onShouldStartLoadWithRequest` event

I would like to suggest

```js
function onShouldStartLoadWithRequest(request){
  // let everything else to the webview
  if (!request || !request.url || request.url.startsWith("http:") || request.url.startsWith("https:")) {
    return true;
  }

  // open natively
  Linking.openURL(request.url).catch(er => { console.log('Failed to open Link:', er.message); });
  return false;
}
```

source : https://stackoverflow.com/a/60883730/1513380

Is it possible?

**Comment by Thaina** [comment]
Further investigation seem to be the reactnative itself not handle the `intent://` url scheme

https://github.com/facebook/react-native/pull/31836

So we could try to make the reactnative team to fix this then wait metamask to rebuild a new version. Or metamask might try to handle `intent:` scheme with the intent URL parser in the mean time ?

**Comment by Thaina** [comment]
Another thing I would like to be considered

Given that firebase dynamic link, `$projectname$.page.link`, has this domain pattern and normal browser could handle this link. Maybe it would be better to detect `.page.link/` in url and use `Linking.openURL` for this domain (with `onShouldStartLoadWithRequest` ?)

**Comment by AlexJupiter** [comment]
This seems like a natural user journey that we should try and support.

**Comment by Thaina** [comment]
Are there any progress on this?

**Comment by lixin9311** [comment]
It might be related to Universal Link handling if you are on iOS.
It is said, a Universal Link can only be activated by user interaction.
Perhaps your codes are like
```javascript
setTimeout( () => { window.location.href = "https://yourapp.page.link/hook"; }, 1000);
```
Then it won't work.

But after I changed it to
```javascript
someBtn.onclick = () => { window.location.href = "https://yourapp.page.link/hook"; };
```
It works just fine.

Did anyone know how to programmatically navigate users back to our Apps?

**Comment by Dipankershah** [comment]
Is that issue fixed? I'm getting the same problem. I cannot redirect from metamask browser to my app by gaggle://home link

**Comment by omnat** [comment]
@andreahaku @ezgi-cengiz there may be some limitations in scalability on supporting link back to dapps, but I'd defer to your judgment on how we can support this issue.

**Comment by AlexHerman1** [comment]
@gantunesr  we have users reporting this error when attempting to list NFT's on opensea.

ZD 931973 and 933120

**Comment by vildantursic** [comment]
Hi everyone,
I've been searching for solution where I would be able to redirect user back to browser app after he connects his wallet.
I don't know if that would be possible, since WalletConnect had to implement whole bunch of stuff to make it work.

My idea was to use deep link in format
https://metamask.app.link/dapp/myapp.com&redirect=true&function=auth
or in case of message signature
https://metamask.app.link/dapp/myapp.com&redirect=true&function=signMessage

Where after the function is done user would be redirected /dapp/<url> URL which is defined in deeplink.

Any ideas, maybe temporary solutions are welcome 😁

**Comment by Thaina** [comment]
Nearly 3 years passed and this bug still persist

**Comment by christopherferreira9** [comment]
Hi all! Is this issue still applicable?

**Comment by Thaina** [comment]
So metamask not in development anymore?

**Comment by Thaina** [comment]
So would it be fix or will be closed?

**Comment by Thaina** [comment]
Is this problem still not being solved?

**Comment by omnat** [comment]
cc @andreahaku @adamceresko
