### ISSUE TITLE
home.metamask.io not loading on MMM 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/metamask-mobile#1635]
**Describe the bug**
Some users are reporting the inability to load home.metamask.io (our homepage).

**To Reproduce**
Once the page goes blank, they are unable to reload it.  Restarting the app, or restarting the device does not seem to fix.

**Smartphone (please complete the following information):**
 - Device: Andoid 9, MMM v.0.2.16

Support ticket #s to reference: 38116, 38102

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? Some users are essentially unable to visit web3 sites.  Critical function to our app at this time.
- Add stats if available on % of customers impacted Maybe not all Android, it's hard to determine how many/ % of users.
- Is this visible to all users? It seems to impact Android only.  
- Is this tech debt?

**Comment by ibrahimtaveras00** [comment]
I found a way to reproduce this 

Go to Browser, and start opening new tabs until you see the blank white screen 

or have 2 new tabs open > kill app > relaunch app > go to other new tab and it will be blank

seen here = https://recordit.co/bWKFA8nQH2 on current 0.2.18 branch 

Maybe related to new home dapps @estebanmino @omnat since the above user is on 0.2.16 I don't think it's release related!?!?
