### ISSUE TITLE
Requested feature: Allow password/biometrics menu to lock account without requiring funding of the account

### ISSUE THREAD

**Issue by mokahless** [MetaMask/metamask-mobile#1748]
Version 0.2.19
-"privacy & security" menu does not have any options related to passwords or biometrics.
-no prompt to create password on initial account creation, nor any prompts to back up seed.
-wallet does not lock because no password can be added.
-Apparently this menu appears once you add funds to your account but I'm not testing this out at current ETH transaction fee rates.

**Comment by omnat** [comment]
Thank you for your thoughtful feedback. 

> -"privacy & security" menu does not have any options related to passwords or biometrics.

You can find **Sign-in with Touch ID** in your Privacy and Security settings.

> -no prompt to create password on initial account creation, nor any prompts to back up seed.
> -wallet does not lock because no password can be added.

Upcoming release is fixing this.

**Comment by ibrahimtaveras00** [comment]
@mokahless we have done several releases since 0.2.19.  Please update to latest version, v1.0.8 and check out the updates we have on the Settings > Security & Privacy page where you can update password and biometrics security features.

![Screen Shot 2020-12-18 at 3 25 48 PM](https://user-images.githubusercontent.com/41752922/102658333-5e905c00-4145-11eb-83ad-287d3de583b7.png)
