### ISSUE TITLE
Run metamask locally and connect to Ganache

### ISSUE THREAD

**Issue by simibac** [MetaMask/metamask-mobile#1774]
How can I connect metamask mobile running locally on my ios simulator to my ganache blockchain? Is that even possible?

**Comment by beccon4** [comment]
Yes it is. Ganache to the outside looks like any Ethereum node. You should try to open a private network and connect to the machine Ganache is running on with the port 8545.

**Comment by EtDu** [comment]
Hey @simibac 

1) When you open ganache, set your hostname as <your-local-IP> instead of 127.0.0.1 (localhost). 
2) In MM mobile Settings > Networks > Add Network and fill in the details.
3) If you're running on a phone, make sure it's connected to the same wifi network as your computer, otherwise it should work fine on a simulator.
