### ISSUE TITLE
[ANDROID] Invalid value for 'projectId': "undefined" 

### ISSUE THREAD

**Issue by DefiOfThrones** [MetaMask/metamask-mobile#1984]
Hello I'm trying to start a debug build of Metamask Android version but I'm facing an issue and I don't find any way to contact the Metamask Community (if there is one).

**Describe the bug**
Here is the exact error : [Error: Invalid value for 'projectId': "undefined"]

I suspect the fact that I didn't fill the file .android.env with but I'm not sure.
export MM_FOX_CODE=
export MM_BRANCH_KEY_TEST=
export MM_BRANCH_KEY_LIVE=
export MM_MIXPANEL_TOKEN=

If the issue is related, where can I find the values ?

**Screenshots**
![Screenshot from 2020-11-12 01-14-15](https://user-images.githubusercontent.com/69632139/98879607-3f3b4a80-2486-11eb-9c97-75371a294ae4.png)

**To Reproduce**
- Clone the git repository
- yarn install
- mv .android.env.example .android.env
- cd android
- yarn start:android

**Expected behavior**
The app starts correctly.

**Smartphone (please complete the following information):**
- Pixel 2 API 29 ANdroid 10.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by estebanmino** [comment]
hey @DefiOfThrones can you follow this format in your `js.env` file? https://github.com/MetaMask/metamask-mobile/blob/develop/.js.env.example

**Comment by DefiOfThrones** [comment]
Hello,

Thx you for your reply, now I have a similar error without undefined.

![Screenshot from 2020-11-12 19-58-49](https://user-images.githubusercontent.com/69632139/98983846-ae19b180-2521-11eb-8e03-451bed719521.png)

**Comment by stringcode86** [comment]
I have encountered same issue. I did some digging. This started to occurring at this commit (infura v3 update) https://github.com/MetaMask/metamask-mobile/commit/c74ce8902c5e799a87555545949b447a9ab1b950. It started occurring because infura now throws exception if `projectId` is undefined or empty string. Quick and dirty workaround is in `Engine.js`
```
new NetworkController(
    {
	infuraProjectId: 'null', // instead of process.env.MM_INFURA_PROJECT_ID,
```
Root cause seems to be that .ios.env (and or .android.env, .js.env) variables are not being loaded
```
Logger.log(process.env);
>  [MetaMask DEBUG]: {"NODE_ENV": "development"}
```

even when changing .ios.env, .android.env, .js.env to
```
MM_FOX_CODE = 'null'
MM_BRANCH_KEY_TEST = 'null'
MM_BRANCH_KEY_LIVE = 'null'
MM_PUBNUB_SUB_KEY = 'null'
MM_PUBNUB_PUB_KEY = 'null'
MM_OPENSEA_KEY = 'null'
MM_INFURA_PROJECT_ID = 'null'
```
with or without `export` in front of the values. I ran `yarn clean` each time I change the values. 
This is as far as I got, could not figure out why `process.env` does not load values from .ios.env, .android.env, .js.env
