### ISSUE TITLE
Remove Ethereum tokens from the 'Add token' dropdown when on Custom Networks

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-mobile#2394]
Do not show the tokens from Ethereum mainnet in the 'Add token' dropdown list when the user is on a custom network (like BSC, etc.). Continue to show the Ethereum mainnet tokens for the test nets (Ropston, Rinkeby, Kovan, Goerli). 

### Context on tokens being network-specific

DAI needs to be minted separately on different chains - they aren't equivalent, they have different token addresses. User is trusting the network when they are adding a custom token. So, Matic, xDAI, BSC all have 'DAI' (with different token addresses), so users who are trying to move DAI from 1 network to another, then you have to go via a bridge (an application that interacts with the 2 chains to make this transfer of assets).. BUT, users don't know they have to do this via a bridge (NOT MetaMask) - if they do this without bridge then users lose their money.

**Comment by cjeria** [comment]
Since this issue is related to the [add token issue](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2409) Is it possible to detect when the user is trying to add Ethereum tokens when on a non-mainnet network? If so, I was thinking we should suggest to the user to switch to mainnet within the empty state and vis-a-versa (if on mainnet, and they are trying to add BSC token).

Alternatively, what if we add a network dropdown on all custom add network screens (no matter the network) that way if a user is on mainnet and they are trying to add a custom chain token, they can do so from mainnet? cc @omnat @estebanmino

**Comment by mobularay** [comment]
I checked the attached PR as well, it is unclear if this ticket is at dev review status, or QA status. Pls add proper labels, thanks so much! @estebanmino

**Comment by mobularay** [comment]
Does not need QA - can be part of regression. ALready dev-reviewed by @andrepimenta
