### ISSUE TITLE
Send NFT collectibles will fail when add it with a decimal number of tokenId.

### ISSUE THREAD

**Issue by lolieatapple** [MetaMask/metamask-mobile#2423]
Send NFT collectibles will fail when add it with a decimal number of tokenId.

I add a NFT collectibles with tokenId: 120

It send failed when I try to send it to another account.

But I successed in transfer it in myetherwallet with ABI.

I get the transaction data from the failed tx and successed tx.

success data:

0x23b872dd0000000000000000000000004cf0a877e906dead748a41ae7da8c220e4247d9e0000000000000000000000005560af0f46d00fcea88627a9df7a4798b1b109610000000000000000000000000000000000000000000000000000000000000078

failed data:

0x23b872dd0000000000000000000000004cf0a877e906dead748a41ae7da8c220e4247d9e0000000000000000000000005560af0f46d00fcea88627a9df7a4798b1b109610000000000000000000000000000000000000000000000000000000000000120

At the end of the data, I see 78 and 120.

Apparently, Metamask Mobile treated my decimal Tokenid 120 as hexadecimal. It leads to failure.

Please fix it, thanks.

**Comment by lolieatapple** [comment]
And I found I can't input hexadecimal value when add NFT by tokenId. I try to paste hexadecimal, and it works well in transfer.

**Comment by moohooooo** [comment]
I got same issue too.

Try to sent NFT #24 ... then #36 sent out
P.S. 24 = 0x24 = 36

This is "Critical Bug" Sir!

**Comment by moohooooo** [comment]
How is it going? This is still an issue!

I try to send #475
![image](https://user-images.githubusercontent.com/128964/113971638-59295f80-9863-11eb-8163-191f397daf00.png)


But it sent #1141
![image](https://user-images.githubusercontent.com/128964/113971641-5c245000-9863-11eb-8f49-9905b268f1d7.png)


So, it means ... try to input as Decimal but it sent as HEX that's why it changed from 475 to 1141
![image](https://user-images.githubusercontent.com/128964/113971650-60506d80-9863-11eb-9f32-633ade214ebb.png)


And I tried to input 1141.... not work still convert 1141 to Decimal

**Comment by genshimaro** [comment]
Critical ISSUE :
I can't input hexadecimal value when I add NFT by his tokenId.
