### ISSUE TITLE
Maintain `swaps-controller` up to date with `controllers` in next release

### ISSUE THREAD

**Issue by estebanmino** [MetaMask/metamask-mobile#2606]
[This](https://github.com/MetaMask/controllers/pull/447) PR is breaking how `swaps-controller` works since it changed the `BaseController`, we should update it when updating `controllers` otherwise it won't work.

**Comment by mobularay** [comment]
Solutions discussed and agreed on Slack:
* I think we just need to update the BaseController in swaps-controller package when a new version is alive. This is failing https://github.com/MetaMask/controllers/pull/447/files#diff-4e522f2de6de03a4118aaaaa35717e44e81a2e9f1697374b444b472b788ad897R70 because swaps controller is not an instance to of the baseController
* We could fix this in @metamask/controllers as well by using duck-typing instead of instanceof. That would prevent future mismatches from breaking this as well

Mark is implementing the solution; tracking on Mobile board to ensure that once it's done, Mobile team knows about it.

**Comment by wachunei** [comment]
This is resolved by https://github.com/MetaMask/controllers/pull/458
