### ISSUE TITLE
metamask mobile app and desktop extension sync

### ISSUE THREAD

**Issue by druid68** [MetaMask/metamask-mobile#2682]
hey, so im rather new to metamask, and i started on mobile, but now, i cant seem to do be able to use pancakeswap on mobile (i dont know why) so i decided to do it through a desktop, however, i cant seem to sync the accounts ? whenever i try it, it just throws an error at me and suggests i reinstall the app, my question is, will the money i put in be lost ? what should i do ? im sorry if this is a stupid question that doesnt really belong here.

**Comment by Sch00ner** [comment]
Just create the wallet with the seed phrase if the QR code doesn't work. Your money will not be lost if you reinstall because it's not tied to Metamask the application, but rather to the blockchain address you are the owner of. If you import the wallet with the seed phrase, it will give you access to these addresses.

**Comment by gantunesr** [comment]
If you need any further assistance please open a new issue
