### ISSUE TITLE
[EIP1559] Long-term fix for Mobile app crashes when a decimal point is added to gas price

### ISSUE THREAD

**Issue by mobularay** [MetaMask/metamask-mobile#2693]
This ticket covers the long-term fix for [issue 2690](https://github.com/MetaMask/metamask-mobile/issues/2690)

Short-term, simple fix was addressed in [PR 2692](https://github.com/MetaMask/metamask-mobile/pull/2692), which is to prevent the usage of decimal in GWEI

**Comment by jakehaugen** [comment]
From some quick research, if "advanced" type controls are available, decimals are supported. Extension DOES allow decimals. Coinbase wallet DOES allow decimals

Also talked with Brad Decker and he suggests supporting decimals can also help in some developer scenarios. 

1559 should have no impact on this decision.

**Comment by mobularay** [comment]
[Alignment](https://consensys.slack.com/archives/GBW7S9FSN/p1621967333090800) between @wachunei and @omnat is to get this work done as soon as we are able to. This work is ready for development.

**Comment by mobularay** [comment]
Could this work be a dependency within EIP-1559? @rickycodes @wachunei @andrepimenta

**Comment by rickycodes** [comment]
I've touched base with @wachunei and he's already started looking at this. seems fine to include it as part of 1559 to me.

**Comment by wachunei** [comment]
@mobularay @rickycodes

I looked at this and here are my thoughts and findings:
- This should no be dependant with EIP1559 work. Since we are going to create EIP1559 UI/UX from scratch we can include the behavior to support decimal Gwei as gas price.
- The current library we are using in this component (`BN.js`) **does not support decimals**.
- There is this other library we have been using for swaps (`bignumber.js`) which does support decimals.
- If we want to switch from `BN.js` to`bignumber.js` we need to consider more time to do it since it requires refactoring the component internals.

**Comment by mobularay** [comment]
Need to have further discussion with Extension as part of EIP-1559 technical planning. 
Also related to Optimism question about gasPrice was being rounded to the nearest 4 decimal places in gwei in MM, which was rounding our gasPrice to 0 gwei
