### ISSUE TITLE
Make the SRP video implementation more fail-proof

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2705]
## Video implementation & error handling

Consider updating the video implementation such that its more fail proof.
- Ensure the video isn't impacting the performance of the issue
- Consider re-using media designs from NFT
- The video should be hosted in a place, where it can't be accidentally deleted like GitHub

**Comment by NicolasMassart** [comment]
Video is actually bundled in the app and not served from github anymore (since 6118b13a69052fe7d2dc5c0fe1d6f7906c94db8f ) including subtitles.
We keep video and subtitles path unchanged on Github in case someone has a very old app version that accesses it online from GH, but I think we don't have these versions anymore in the wild.

See [app/videos/README.md](https://github.com/MetaMask/metamask-mobile/blob/00da3d98024ef438e4ffb7e16a05ec175203a4f4/app/videos/README.md) and local loading of the video as evidence in [SeedPhraseVideo](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/UI/SeedPhraseVideo/index.js#L7-L7)
