### ISSUE TITLE
Enable Seed Phrase import

### ISSUE THREAD

**Issue by mightypenguin** [MetaMask/metamask-mobile#3058]
**Describe the usability problem**
Mobile client does not support Seed Phrase import of account like browser extension.
Some wallets are only backed up with seed phrases and cannot be directly imported into Mobile Metamask.
e.g. Grid+ Lattice

**Comment by rickycodes** [comment]
seed phrase import is supported and part of the on-boarding flow. this has worked since v1

it's the first option on the wallet setup:

![image](https://user-images.githubusercontent.com/675259/141833577-d5b949ab-dca6-4cec-adde-d8f5dbedf1b2.png)

![image](https://user-images.githubusercontent.com/675259/141833683-37851d08-aff4-4db6-996f-73e040dd30c8.png)
