### ISSUE TITLE
Opensea API is probably changed, lot of projects get issue: "Unidentified Contract"  

### ISSUE THREAD

**Issue by Toni-d-e-v** [MetaMask/metamask-mobile#3518]
**Describe the bug**
On some nft projects it does not display name but "Unidentified Contract"  

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:
1. Add contract
2. See that it does not display a name

**Expected behavior**
Project name

**Screenshots**

![image](https://user-images.githubusercontent.com/62844491/146772014-54467f79-acb4-4bed-88f0-6bceeee5aaf7.png)

**Comment by gantunesr** [comment]
Hi @Toni-d-e-v,  in which version are you seeing this issue? It should be solved in v3.8.0

**Comment by Toni-d-e-v** [comment]
Yeah I'm on that ver same issue

**Comment by gantunesr** [comment]
Which is the address of this collection?

**Comment by gantunesr** [comment]
Hi @Toni-d-e-v, looks like this issue is solved in v3.8.0, a quick solution to your situation would be removing those NFTs and adding it again, the collection name should appear correctly after that. I'll update the solution so this step would not be required in future versions. Thanks for bringing this to my attention!!

![Screen Shot 2021-12-21 at 19 43 19](https://user-images.githubusercontent.com/17601467/147007099-92a108d9-8378-49a2-bdf1-5597daf5a587.png)
