### ISSUE TITLE
NFT Collection logo not appearing

### ISSUE THREAD

**Issue by dspencer926** [MetaMask/metamask-mobile#3681]
### **Description**

I can't figure out how to display a logo for an NFT collection; instead I get a gray box with the first letter of the name of the collection.  I've looked through some of the MM code and it looks like the image url is coming from a field called `logo`.  I've tried putting a field `logo` in the metadata for the collection, linking to a file on IPFS, but it still doesn't work.  Can anyone please give me some insight on how to get an image to display instead of the gray box?

**Comment by gantunesr** [comment]
Hey @dspencer926, currently the logo url is being fetched from the OpenSea API, the reason for this is because NFTs have only a basic metadata structure that is defined in the [EIP](https://eips.ethereum.org/EIPS/eip-721#specification) and we can trust that most developer will use that structure, so the app only gets the name, description, symbol, and asset url (image) from the blockchain. This is challenging for us since every developer can use their own metadata structure to include other attributes like a logo, for example,

Case 1: 

```json
{
  "name": "My 1st Collection",
  "description": "Just a standard ERC721 collection",
  "logo": "url://..."
}
```

Case 2: 

```json
{
  "name": "My 1st Collection",
  "description": "Just a standard ERC721 collection",
  "logo": {
    "size": "small",
    "url": "url://...",
    
  }
}
```

We are working to improve this, but for the moment the only way to add a logo to a collection is to set it with OpenSea

**Comment by dspencer926** [comment]
Thanks for your response @gantunesr!  I should have added more details.  I have a metadata file on ipfs in the following format as specified in the OpenSea documentation (https://docs.opensea.io/docs/contract-level-metadata)

```
{
  "name": "OpenSea Creatures",
  "description": "OpenSea Creatures are adorable aquatic beings primarily for demonstrating what can be done using the OpenSea platform. Adopt one today to try out all the OpenSea buying, selling, and bidding feature set.",
  "image": "https://openseacreatures.io/image.png",
  "external_link": "https://openseacreatures.io",
  "seller_fee_basis_points": 100, # Indicates a 1% seller fee.
  "fee_recipient": "0xA97F337c39cccE66adfeCB2BF99C1DdC54C2D721" # Where seller fees will be paid to.
}
```
And I've attempted to link my contract to this json file by adding a contractURI function that returns the link to that file.

When I hit the endpoint https://api.opensea.io/api/v1/asset_contract/, I'm able to see all the metadata for my contract, including the data that comes from the contract level metadata json file referenced above, and when I look at my contract on OpenSea, I see the logo on their page.  However it's still not appearing in Metamask.  Is there something else I'm still missing?

**Comment by gantunesr** [comment]
@dspencer926 can you share with me the address of the collectible?

The app is fetching the logo from the collection object, the key in this case would be `image_url`, you can see this change in the [Controllers PR #628](https://github.com/MetaMask/controllers/pull/628/files#:~:text=image_url%3A%20string%20%7C%20null%3B-,collection%3A%20%7B,%7D%3B,-%7D)
