### ISSUE TITLE
ENS confusables should not include the regular letter "m"

### ISSUE THREAD

**Issue by serenae-fansubs** [MetaMask/metamask-mobile#3799]
**Describe the bug**
When an ENS name is entered and contains the letter "m", Metamask flags this (incorrectly in my opinion) as a confusable character. This also appears to happen to the digits "0" and "1".

**Screenshots**
![image](https://user-images.githubusercontent.com/95138671/155265337-6a2785ab-e5de-446a-ade2-4ebc83a8c8d6.png)

**To Reproduce**
Enter any ENS name that contains "m", like temp.eth
Enter any ENS name that contains "0", like 0xbitcoin.eth
Enter any ENS name that contains "1", like 1bitcoin.eth

**Expected behavior**
Metamask should not display that "potential scam" warning when the name just has a letter m in it

In general, if a name is only comprised of "regular" characters [a-z0-9], the confusable warning message should not appear.

**Comment by serenae-fansubs** [comment]
I see that this was pointed out in multiple places on the original feature, but was dismissed as "not a bug".

**Comment by rickycodes** [comment]
hi @serenae-fansubs 

m, 0 and 1 are all valid confusables. the library we're using to flag these is just pulling from a standard document: http://www.unicode.org/reports/tr39/. 

here's the full list: https://unicode.org/Public/security/10.0.0/confusables.txt, you can see the m -> rn case.

![image](https://user-images.githubusercontent.com/675259/158660236-94a98c21-008f-4bb1-98a5-a5110c45058e.png)

for the 0 & 1 cases the mapping is:
```
"0": "O",
 "1": "l",
 ```
because 0 can be confused with O and 1 can be confused with l.

The extension does something similar here:

![image](https://user-images.githubusercontent.com/675259/158660542-35eccd92-6937-4d58-a8c8-b69b8a66ceaf.png)

I've opened #3902 in a effort to better explain why characters get flagged in ENS names. I hope this helps.
