### ISSUE TITLE
Cannot get access to camera and mic.

### ISSUE THREAD

**Issue by uriee** [MetaMask/metamask-mobile#3907]
When trying to establish a connection to the camera and microphone using the html5 command getUserMedia
it returns a  "NotAllowedError" error.

We ask for a media connection :
```
navigator.mediaDevices.getUserMedia({
      audio: true,
      video: true
    }).catch(e => alert('getUserMedia() error: ' + e.name))

```
 this request is answered with a "NotAllowedError"

On other browsers, it returns the audio and video streams.

 - Device: pixle 6
 - OS: android 12
 - metamask  app version : 4.2.2 (834)

**Comment by gantunesr** [comment]
Hey @urie, we are aware of this issue and it'll be addressed in a future development. I'll keep this issue updated.

**Comment by jnbt** [comment]
FYR: It works for me using the iOS app.

**Comment by MnogoDobur** [comment]
Has any work been made on this issue?? It has been over 8 months since it has been found out and it's crucial for certain dapps.

**Comment by MnogoDobur** [comment]
Dear all, has there been anything done regarding this issue? It is nearly a year since it has been found..

Tested it today - both on IOS and Android, Metamask's browser cannot use the microphone of the device. On IOS the app crashes and on Android it just returns "No audio".
Please update us when possible.
