### ISSUE TITLE
So when I used my secret recovery phrase i didn’t get my account back I had the wallet but not the account and all my nats from mintable disapperead and I forgot my private key please fix this and please give me back my account: Pog_memes

### ISSUE THREAD

**Issue by Pogggggggggggggg** [MetaMask/metamask-mobile#3992]
**Describe the bug**
_A clear and concise description of what the bug is_

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_

**To Reproduce**
_Steps to reproduce the behavior_

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by gantunesr** [comment]
Due to the nature of your issue and the fact GitHub is a public forum, we kindly request you get in contact with our support team so that we can help you one-on-one without leaking personal information like your addresses and on-chain activity.

You can access all of our helpful articles and contact our team via https://metamask.zendesk.com/
