### ISSUE TITLE
Ошибка связанная с достижением пределом хранилища

### ISSUE THREAD

**Issue by Djoni0603** [MetaMask/metamask-mobile#4141]
![Screenshot_2022-04-22-14-50-49-038_io metamask](https://user-images.githubusercontent.com/39297880/164709818-d36f1b4b-b367-4561-be88-06a7957c8fad.jpg)
Здравствуйте, не могу войти в кошелек. Сид фраза утеряна чтоб удалить и по новой привязать старый кошелек, есть возможность убрать ошибку чтоб я смог войти в свой кошелек, или узнать свою сид фразу для восстановления, на этом кошельке весь мой труд, и много чего завязано, что мне сделать чтоб убрать ошибку не удаляя кошелек, чтоб я мог войти по паролю.

**Comment by tommasini** [comment]
@Djoni0603 you will have to use your secret recovery phrase to set up a new password
You can follow the instructions [here](https://metamask.zendesk.com/hc/en-us/articles/360015289612-How-to-restore-your-MetaMask-wallet-from-Secret-Recovery-Phrase)

I will close this issue since it's not an issue with the mobile app.

**Comment by smok1s** [comment]
Как решили проблему?
