### ISSUE TITLE
[Proposal] User must backup their SRP

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4372]
## Background
- currently users can `skip` the srp backup phase of onboarding when generating their wallet
- we then annoy them with prompts about the importance of backing it up

## What
- once a user enters the wallet creation phase, we should not allow them to skip the backup phase
- To allow users to "check out" the app, we could allow them to "sign is a guest" and as soon as they tried to use a feature that requires a wallet, we launch them into the wallet creation phase where a backup is mandatory

**Comment by owencraston** [comment]
It seems that once users have funds we force them to backup their seed phrase so this is not an issue

**Comment by anarchymachines** [comment]
I know this issue is closed, but this is super annoying. I just want to use MetaMask to manage an account that I want to import via private key...but I have to create an account first. Fine. I am able to skip backing up the recovery phrase that I do not need - great. But then after I import my private key, because I have "added value" it now is forcing me to backup the recovery phrase (that has nothing to do with the "value" I added). So, if I want to continue, I have to complete the tedious task of confirming that I have written down the recovery phrase (that I do not need). I do not want to do that. I would rather document my frustration here...this is slightly less annoying because at least there is a chance that something useful might happen as a result (albeit a small chance...or a "fat" one, as it were).

Anyway...the rest of the app is pretty cool.
