### ISSUE TITLE
[5.5][Ledger Integration] Signing a message while there is still a pending signature on the device results in the LedgerConfirmationModal saying the device is disconnected

### ISSUE THREAD

**Issue by owencraston** [MetaMask/metamask-mobile#4457]
### **Description**

- Signing a message while there is still a pending signature on the device results in the LedgerConfirmationModal saying the device is disconnected
- discovered on [ledger-modals](https://github.com/MetaMask/metamask-mobile/tree/ledger-modals) branch

### **To reproduce**

- connect the ledger
- go to [https://metamask.github.io/test-dapp/](https://metamask.github.io/test-dapp/)
- sign transactions
- reject the transaction on the modal
- the modal dismisses `but the signature request is still present on the device`
- then press the sign button again
- notice the connection state says the device is disconnected when it is connected
- you can sign a transaction after to show that it is indeed connected

### **Acceptance Criteria**
- either the first signing should have been cancelled or we should have a state that indicates there is still suer action required on the device

### **References**

-  Discovered in [this PR](https://github.com/MetaMask/metamask-mobile/pull/4426)

### Video

https://user-images.githubusercontent.com/22918444/172209307-34670472-37d7-42ba-9b86-aec00659ebbf.mp4

**Comment by zoltanarvai** [comment]
Tricky one. We can show something else instead of the disconnected UI however we cannot cancel the transaction programatically on the device. It's "stuck" there. What would be the best way to handle this? Another issue is that we can't really know it's not been accepted. I think we should remove the Reject button as it brings us to an unresolvable state.

**Comment by AlexJupiter** [comment]
If we can't cancel the transaction on the device or know whether the user has signed the transaction on the device then I agree we should probably remove the "Reject" button (in the above video at 0.06). That said, I feel like there should be a way of knowing if the user has signed the transaction or not on their Ledger since that transaction was initiated by MetaMask but I could well be wrong here. 

I could also imagine a user ending up in this situation if they close their MetaMask app (either accidentally or on purpose) before signing the transaction on their Ledger. So I do think we need an error state for the scenario where the screen states something like "Please confirm or reject the transaction on your Ledger device before attempting a new transaction."

**Comment by AlexJupiter** [comment]
To solve this, we can:
1. Remove the reject button (optional)
2. Update the error handling to take care of busy state on the device (@zoltanarvai to focus on this soon)

**Comment by AlexJupiter** [comment]
@jakehaugen do you have any thoughts on removing the "Reject" button to try and reduce the chances of a user ending up in this error situation? One disadvantage I see is that we're reducing choice for the user and also the user could end up in this situation by swiping down on the action sheet anyway.

**Comment by zoltana-ledger** [comment]
Addressed this in the PR: https://github.com/MetaMask/metamask-mobile/pull/4534

**Comment by plasmacorral** [comment]
https://github.com/MetaMask/metamask-mobile/issues/4455#issuecomment-1248714355

**Comment by plasmacorral** [comment]
resolved in 952
