### ISSUE TITLE
Android metamask not showing the Image of the NFT 

### ISSUE THREAD

**Issue by mahafan** [MetaMask/metamask-mobile#4542]
**Describe the bug**
_Android metamask not showing the Image of the NFT but for the same NFT it was import to an IOS metamask it show the images_

**Screenshots**
_If applicable, add screenshots or links to help explain your problem_
![IMG_4400](https://user-images.githubusercontent.com/16384534/174558456-970a4812-384a-4960-a178-5bd536d20a44.JPG)

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to '...' nft 
2. Click on '....'click import nft
3. Scroll down to '....'paste the contract and token id 
4. See error then the screen will rollback to nft tab and nft will show up with only the name and the token id no image

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] vivo
 - OS: [e.g. iOS8.1]10
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask 5.2.0(913)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user? not critical
- Add stats if available on % of customers impacted 
- Is this visible to all users? i dont know maybe 
- Is this tech debt? dont know

**Comment by seaona** [comment]
This issue is still present in prod. I can see the NFT image in Extension but not in Mobile.
**Repro:**
1. Go to the test dapp
2. Deploy an NFT contract
3. Mint a token
4. Import it to the wallet
5. See no image is displayed
6. Do the same in Extension --- see image is displayed

![Screenshot from 2024-04-23 12-04-29](https://github.com/MetaMask/metamask-mobile/assets/54408225/75c33a73-ff02-4713-b0f1-d828268c575f)
