### ISSUE TITLE
Mobile: TypeError   forEach([native code])  undefined is not an object (evaluating 't.toLowerCase') error occurring on growing number of devices 

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#4738]
**Describe the bug**
CS is reporting a growing number of Sentry errors showing for the following.....

https://sentry.io/organizations/metamask/issues/2972644485/?project=2299799&referrer=slack

CS team suspects this error is occurring after launching the mobile app but have not been able to get steps to reproduce.

**Screenshots**
TBD

**To Reproduce**
TBD

**Expected behavior**
Error does not occur while using mobile app.

**Smartphone (please complete the following information):**
 - App Version [e.g. 1.0.0] - find version number in app from Settings > About MetaMask

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by AlexHerman1** [comment]
we received a zendesk ticket indicating a similar error `TypeError: undefined is not an object (evaluating 'e.toLowerCase')`

5.14.0 on an android 13 phone (#996061)

**Comment by AlexHerman1** [comment]
i think this is still relevant

**Comment by hesterbruikman** [comment]
Adding to this issue, a [recording](https://drive.google.com/file/d/1Lkr1oO2LUttlbAAwe8m4Di8a-wRqBkcg/view) from https://consensyssoftware.atlassian.net/browse/MMBUGS-71 where this issue is shown after providing the password at an attempt to Reveal SRP.

1. Open app
2. Unlock with biometrics
3. Switch from custom RPC endpoint to default Ethereum Mainnet
4. Wallet not loading
5. Balance in drawer showing $0 (not loading)
6. Create new account not responding
7. `Security and Privacy` > `Reveal SRP` > `Complete quiz`
8. `Enter password`
9. `Hold to Reveal SRP` > No response, modal disappears and can be triggered again by tapping Next
10. Navigate back to `Settings`
11. Close `Settings`
12. Error is shown
