### ISSUE TITLE
Biometric login fails with Unknown error: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference

### ISSUE THREAD

**Issue by AlexHerman1** [MetaMask/metamask-mobile#4874]
**Describe the bug**
MM Mobile biometric login fails and displays the above error

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/38788573/184964683-250b8e34-5673-4dec-8efd-7be9e895be81.png)

**To Reproduce**
I do not have an android device to try to repro on. There is a sentry report for this issue.

**Expected behavior**
Be able to login.

**Smartphone (please complete the following information):**
 - Device: Huawei Nova 7 i
 - OS: Android (not sure of version)
 - App Version: 5.4.0

**Comment by tommasini** [comment]
@AlexHerman1 Thanks! Do we have this error appearing to different users or different devices?

**Comment by AlexHerman1** [comment]
@tommasini  we have 8 total tickets on this, seems to appear in a variety of different scenarios. multiple people reported from log in screen, two seem to have it upon trying to use biometrics. i am sure they are not all on same device, it looks like mainly an android issue.

**Comment by cortisiko** [comment]
relates to https://github.com/MetaMask/metamask-mobile/issues/4840

**Comment by wadeking98** [comment]
I ran into this issue on an app that I'm creating. For me the issue was due to the fact that I set the storage type to `Keychain.STORAGE_TYPE.AES` and saved password using `Keychain.setGenericPassword(...)`, then later in the application it changes the storage type to `Keychain.STORAGE_TYPE.RSA` and calls the same `setGenericPassword` method but with the storage type being RSA instead of AES. To fix this you need to call `Keychain.resetGenericPassword(...)` before you call `Keychain.setGenericPassword(...)` the second time

**Comment by seaona** [comment]
I've encountered this same error while clicking on Import a token. After dismissing the error I could see how the Import a token link was then greyed out (not clickable) and no other function responded  / MM stayed frozen.

I solved this by re-starting the app (closing and opening again).

![Screenshot from 2023-05-04 12-40-16](https://user-images.githubusercontent.com/54408225/236183876-a2b782ef-667e-4c6e-bc98-6ce2eeaf4f5d.png)
