### ISSUE TITLE
Sign message not show up when connect with deeplink (IOS)

### ISSUE THREAD

**Issue by hidenxtt2001** [MetaMask/metamask-mobile#5004]
When i create session a from my flutter app with wallet connect,  it open Metamask app but not showing any sign.

https://user-images.githubusercontent.com/63885463/190912156-c9ad7b28-532f-4cb3-8e32-c2290ea5478a.mp4

I have try with android and it work well without any error.

**Comment by tommasini** [comment]
Thanks for reporting @hidenxtt2001, I see that you are using the simulator, can you please try the deep link with a physical device?

**Comment by Cydie** [comment]
Using universal links (`https://metamask.app.link/wc`) is broken since months now on iOS (probably on Android too but most just use the `wc://` deeplink instead, so they'll never notice it).

Direct `metamask://` deep links do work, but they are not the recommended way by WalletConnect to handle redirects, and are not optimal for every use-case.

https://github.com/MetaMask/metamask-mobile/issues/3874
https://github.com/MetaMask/metamask-mobile/issues/4623
https://github.com/MetaMask/metamask-mobile/issues/4955
https://github.com/MetaMask/metamask-mobile/issues/5004

Please guys fix this issue

**Comment by JoeSteven** [comment]
Facing the similar issue here, and i found how to reproduce it. @tommasini 
1. open metamask first, and switch it to background for like one or two minutes, in order to let it show the Fingerprint verification page
2. use any WalletConnect client , OpenSea for example, click connect wallet and choose metamask
3. MetaMask will be open and display the Fingerprint verification page
4. after verified, MetaMask will enter the home page, but no bottom sheet will display

I found it only happens when the MetaMask is need verification, But if i killed it, the connection bottom sheet will be display as expect.

MetaMask version:5.7.0
platform: Android
Client app: OpenSea and the demo I wrote:https://github.com/JoeSteven/KMP-WalletConnect
Device: Pixel 6
deeplink starts with: wc:

**Comment by Cydie** [comment]
> Facing the similar issue here, and i found how to reproduce it. @tommasini
> 
> 1. open metamask first, and switch it to background for like one or two minutes, in order to let it show the Fingerprint verification page
> 2. use any WalletConnect client , OpenSea for example, click connect wallet and choose metamask
> 3. MetaMask will be open and display the Fingerprint verification page
> 4. after verified, MetaMask will enter the home page, but no bottom sheet will display
> 
> I found it only happens when the MetaMask is need verification, But if i killed it, the connection bottom sheet will be display as expect.
> 
> MetaMask version:5.7.0 platform: Android Client app: OpenSea and the demo I wrote:https://github.com/JoeSteven/KMP-WalletConnect Device: Pixel 6 deeplink starts with: wc:

I don't see how your description fits our issue. It may be related in some way but it's not the same issue this thread is about

**Comment by cortisiko** [comment]
hey @hidenxtt2001 can you share your flutter app so we can try to reproduce the issue? Thanks!

**Comment by w4-jake** [comment]
Hey there,

I made a [sample Flutter app](https://github.com/w4-jake/flutter_wallet_connect_metamask) that I'm hoping will be helpful for checking this issue on multiple platforms:

- Android native
- iOS native
- **mobile web on browser on Android device**
- mobile web on browser on iOS device
- PC web (QR scan)

I personally made this app in the hopes that it will assist the Metamask team in looking into this same issue that some users have seen when opening a WalletConnect deep link or universal link to Metamask from the **mobile web build on browsers like Chrome, Firefox, DuckDuckGo on an Android device** (please see #4955).

I haven't been able to test yet on a native build in an iOS device, but hopefully this app can help the Metamask team try to reproduce this issue as well on iOS, so I'm leaving it here as well! (cc: @cortisiko)

Please let me know if there's any more information I can give or support I can provide in reproducing and looking into this issue. I would love to help!
