### ISSUE TITLE
Metamask Mobile unable to connect to network

### ISSUE THREAD

**Issue by trevorsc19** [MetaMask/metamask-mobile#5186]
**Describe the bug**
Mobile application unable to connect to private Ethereum network. Showing an error message saying "Could not fetch Chain ID. Is your RPC URL correct?" 

This is not a single user issue, we have multiple users who are having the same issue as well.

**Screenshots**
Image 1 shows an unsuccessful connection to my private network through the mobile app
![IMG_3267](https://user-images.githubusercontent.com/30576577/199234539-3ce6993e-7d2b-40ca-a116-017976713b17.png)

Images 2 and 3 show a successful connection to my private network through the browser using the same JSON RPC URL and Chain ID
![MMBrowser](https://user-images.githubusercontent.com/30576577/199234565-2048b85d-e992-4d58-a5e6-38a02a202da4.PNG)
![MMBrowser2](https://user-images.githubusercontent.com/30576577/199234567-fa985491-6aff-435b-991c-62e6010ee102.PNG)

**To Reproduce**
1. Go to Kaleido.io
2. Create your own private ethereum network
3. Generate App Credentials
4. Use the resulting JSON/RPC URL with complete App Creds and chain ID to try and connect to MetaMask.

**Expected behavior**
Metamask mobile app should connect to private network. I'm not preventing any calls from Kaleido's side and the same URL works on the browser extension but not on mobile.

**Smartphone (please complete the following information):**
 - iPhone X
 - App Version 5.9

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by olgamartinchik** [comment]
I have the same problem with connection  to private Ethereum network in the mobile version of the wallet! I get an error when trying to connect, but everything works in the browser.

Characteristics of my phone and mobile app:
Phone 6s ios15.6.1
MetaMask v5.9.0(990)

My colleague has the same problem. Characteristics of his phone and mobile app: 
Phone realme 8i  Helio G96
MetaMask 10.21.1

Screenshot with an error:
![image](https://user-images.githubusercontent.com/61679473/199314120-a92dc021-ca8e-4f2e-8932-685b1021b4da.png)

Screenshot of the browser wallet:
![image](https://user-images.githubusercontent.com/61679473/199313909-1b612976-640c-47ec-865b-06aef779f9ce.png)

Assets of my wallet in the browser:
![image](https://user-images.githubusercontent.com/61679473/199317953-d5daec68-689a-4d8b-95d5-a1579fe0679d.png)

**Comment by kthewhispers** [comment]
Yeah this definitely is related to #5210 because this same issue happens on just a regular LAN private test net via RPC.

**Comment by kthewhispers** [comment]
Open up an stdout log of your node and get the IPV4 of your device, enable any kind of verbose logging feature on the node if you can.

Additionally here are some other things to try:

Type the Chain Id in as a 0x prefix hex code.

**Ensure that the SSL CA Certificate is inside the Root Trusted Certificate Authority(CA) in chrome.**

_If these are self-signed certificates, you must add them to your browser's list of certificates in the **Trusted Root CA**_

Do not use the self-signed CA Certificate these for production(release) builds as it would make HTTPS redundant.

Ensure that your node HAS SSL capability and do your due-diligence on what most browser's expect the version of SSL to be.

Personally I believe it would be easier if you just used HTTP for development and then enabled SSL with a reverse proxy that has the SSL capability. If these are all truly private chains then there's no point in using SSL anyway though.

*There could be something wrong with the common name of your domain of your respective SSL .ext file.*

_You must add subdomains to the common name and the IP address of the address your *Node* is listening on._

It's extremely picky if you're writing your own certificates just to have HTTPS in development unless you get it done by a widely Trusted Browser Certificate Authority. 

_**So if you're passing HTTPS to MetaMask, it HAS to be pristinely done for it to work.**_

Since you are using a private chain, **per MetaMask's HTTPS policy listed in _react_native_config.xml and even the android manifest XML file.** Metamask's policies therefore _will accept your RPC as cleartext HTTP:// url_ since it is on the _localhost_ and you're using Metamask Desktop in-browser on the node machine.
