### ISSUE TITLE
Phoenix Blockchain Custom Network not showing gas estimation

### ISSUE THREAD

**Issue by h4xr4nubs** [MetaMask/metamask-mobile#5516]
Gas estimation on custom EVM compatible network not populating, transactions won't push through even after resetting account. Please help!

I'm using MetaMask mobile v5.12.1 and custom network:
Network Name: Phoenix
RPC Url: https://rpc.phoenixplorer.com
Chain ID: 13381
Symbol: PHX
Block Explorer: https://phoenixplorer.com
![Screenshot_20230114-000651](https://user-images.githubusercontent.com/34799222/212458564-b34ab0c4-184d-4b4c-a55e-52453f71cd82.png)

**Comment by cortisiko** [comment]
hey @h4xr4nubs ! Thanks for reporting this issue. The bug has been fixed in https://github.com/MetaMask/metamask-mobile/pull/5439 and will be in version 5.13 which would be released in the coming week or so. I am going to close this issue. After 5.13 is released and the issue still persists feel free to reopen it.
