### ISSUE TITLE
Metamask does not support navigator.clipboard.writeText on Android

### ISSUE THREAD

**Issue by hsuanweifu-sports-inference** [MetaMask/metamask-mobile#6468]
**Describe the bug**
Does not support navigator.clipboard.writeText on Android Phone. I have tested on Android Chrome browser and was working as expected.

**Screenshots**
N/A

**To Reproduce**
1. `<button onClick={() => void (async () => navigator.clipboard.writeText("This is a test").then(() => alert("copied")).catch(() => alert("error")))}>`
2. Click on Button
3. No alert shown / test not copied

**Expected behavior**
1. alert shown
2. test copied

**Smartphone (please complete the following information):**
 - Device: [Pixel 6]
 - OS: [Android]
 - App Version [6.4.0]

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello, @hsuanweifu-sports-inference. Thanks for reporting! I will pass this on to my team.

**Comment by Gowtham118** [comment]
Yes. Even I have faced this issue. I tried to run my DApp on metamask browser which has a copy to clipboard functionality. It uses `navigator.clipboard.writeText` and `document.execCommand` as fallback to copy text.

**Comment by KholdStare** [comment]
@sethkfman @anaamolnar Any updates? It has been several months, and the issue still persists.

**Comment by KholdStare** [comment]
@sethkfman @anaamolnar Not stale.

**Comment by mhmmdhajizade** [comment]
Hi. I have the same problem when opening my dApp on Metamask browser and `navigator.clipboard.writeText` is not working

**Comment by KholdStare** [comment]
@gauthierpetetin Hi, any updates? Thank you.

**Comment by gauthierpetetin** [comment]
Hi @hesterbruikman , is there any update on this issue?

**Comment by hesterbruikman** [comment]
@mhmmdhajizade @KholdStare could share more details about your use case and what is not working please? From the issue I understand that you're looking to add a copy to clipboard button. 

I see this working for example on portfolio.metamask.io and snapshot.org.

**Comment by KholdStare** [comment]
@hesterbruikman Merely seeing if it "works" on other websites is not enough - The original question is specifically about the `navigator.clipboard.writeText` browser API (documented here: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText). A lot of websites (including our own) had to resort to a workaround to make the clipboard functionality work. Thus just testing if the clipboard works on a random website does not address the original concern.

This is what we were forced to do in a polyfills file because the standard `navigator.clipboard.writeText` did not work:

```ts
const writeText = (text: string): Promise<void> => {
  return new Promise((resolve, reject) => {
    let success = false;
    const listener = (e: ClipboardEvent) => {
      e.clipboardData?.setData("text/plain", text);
      e.preventDefault();
      success = true;
    };
    document.addEventListener("copy", listener);
    document.execCommand("copy");
    document.removeEventListener("copy", listener);
    success ? resolve() : reject();
  });
};

// If using metamask on android, fix clipboard
if (
  /android/i.test(navigator.userAgent ?? "") &&
  window?.ethereum?.isMetaMask
) {
  window.navigator.clipboard.writeText = writeText;
}
```

It's been almost a year since the issue was posted, and it seems like `window.navigator.clipboard` has started working in metamask - perhaps it just required an update of the built-in android webview. FYI, I've used this to test: https://codesandbox.io/p/sandbox/trust-wallet-clipboard-test-wgng0?file=%2Fsrc%2Findex.js

**Comment by Cal-L** [comment]
> It's been almost a year since the issue was posted, and it seems like window.navigator.clipboard has started working in metamask - perhaps it just required an update of the built-in android webview.

Glad it's working. Closing issue for now. Please re-open if the issue regresses. Thanks.
