### ISSUE TITLE
WalletConnect not working after update to version 6.6.0

### ISSUE THREAD

**Issue by hadi-norouzi** [MetaMask/metamask-mobile#6532]
**Describe the bug**
I updated my app from play store and after that when i click a button in another app to open matamask through the wallet connect is not working

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Smartphone (please complete the following information):**
 - Device: Pixel 7, Samsung A51
 - OS: Android 13
 - App Version 6.6.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by anaamolnar** [comment]
Hello @hadi-norouzi. Thanks for reporting! Are you trying to connect to your Metamask wallet from another native app, or are you trying to connect your Metamask wallet to a decentralized app using your mobile browser? Please provide more details on this. Thank you!

**Comment by nekotoriy** [comment]
I ran into a problem when connecting the iOS Metamask app via Wallet Connect to dApp. When scanning the QR code, it offers to open the Metamask app, after opening nothing happens.

Expected result - there should be an offer to connect the wallet to the dApp with a signature request.

**Comment by ioridev** [comment]
https://github.com/MetaMask/metamask-mobile/issues/6457
Linking the same issue

**Comment by florin-pop** [comment]
I opened the same issue in the MetaMask SDK repo thinking it might be related to that, but it looks like it could be related to the wallet app.
https://github.com/MetaMask/metamask-ios-sdk/issues/75

I tried on multiple devices with apps like OpenSea and I'm not able to connect the MetaMask wallet because the popup is not being shown. I have no problem connecting other wallets. Please see the linked issue for videos capturing the issue.

**Comment by anaamolnar** [comment]
Hello, @hadi-norouzi. Please let me know if you still experience this issue in the latest version of Metamask.
