### ISSUE TITLE
[Bug] Whenever loading balance is delayed, the Warning for needing more ETH is displayed and cannot perform the tx once the balance is loaded

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#6535]
**Describe the bug**
Whenever there is a delay loading the balance for the selected account, the Warning for needing more ETH for completing the transaction is displayed. The problem is that whenever the balance is loaded, the Warning is still displayed and I cannot proceed with confirming the transaction as the Confirm button is disabled

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/54408225/d3d4d492-b4b7-4004-ab7e-e29d6e912e36

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to test-dapp
2. Simulate a slow response from the getBalance request
3. Click on Send EIP1559
4. See how warning for needing more ETH appears and Confirm button is disabled
5. Wait until correct balance is loaded
6. See how warning is still displayed and Confirm button is still disabled

**Expected behavior**
Whenever we load the balance, the warning should be removed and Confirm button enabled, if there is enough balance.

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android
 - App Version: found in `6.7.1` but possibly an old issue

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by bschorchit** [comment]
Expected behavior:
Not display the warning, but disable the button until we receive the balance

**Comment by cryptotavares** [comment]
The reason why this happens is because we do not have the balance for the account in the redux state (we are getting the accounts and its data using [this selector](https://github.com/MetaMask/metamask-mobile/blob/main/app/selectors/accountTrackerController.ts#L11)).
On the confirmation page we are checking the [selected account balance](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/SendFlow/Confirm/index.js#L628-L637) and if that balance is not greater or equal than the total on the validateAmount we will display the warning.

So how do we get the balance to be available on the redux state? Via the AccountTrackerController. It has a [polling mechanism](https://github.com/MetaMask/core/blob/main/packages/assets-controllers/src/AccountTrackerController.ts#L152-L161) that is triggered every **10s**. In that polling, it syncs the accounts and then [retrieves the balance for the selected account using getBalanceFromChain](https://github.com/MetaMask/core/blob/main/packages/assets-controllers/src/AccountTrackerController.ts#L169-L183) (or to all accounts depending on the user preferences). Aaand the `getBalanceFromChain` uses the [util `safelyExecuteWithTimeout`](https://github.com/MetaMask/core/blob/main/packages/controller-utils/src/util.ts#L226) which has a default timeout of 500ms. So if the getBalance request always takes more than **500ms**, we will never get the account balances. Meaning that we will have the warning displayed and the confirm button disabled.

@bschorchit To properly solve this we would need the controller to flag to the UI, if it is getting the balance for the 1st time but the request hasn't been resolved yet, or if it tried and failed because the request took too long (and display the correct information/behaviour to the user). Also it would be useful to have a timestamp from the latest balance update (as if too much time has passed, we cannot be confident on the account exact balance and might end up allowing the user to submit trx that will fail).

As we do not have that capability yet, I believe that the current fix should be implementing the behaviour that @seaona stated on the issue description. Whenever the selected account balance updates, we should remove the warning and enable the confirm button.

**Comment by jpuri** [comment]
Hey @seaona : can you plz detail how can I do this step:

> Simulate a slow response from the getBalance request

**Comment by seaona** [comment]
- on real devices you could do similarly as what we do for Extension (customize Network throttling):
https://www.browserstack.com/guide/how-to-simulate-slow-network-conditions

- on the emulator, it was mentioned by @digiwand and @cryptotavares that it should be possible adding some delay on the code level

**Comment by jpuri** [comment]
@cryptotavares : it may also be a good approach to not show error message if balance is returned by controller is undefined, so we know that it has not yet been fetched for the first time even.

It will not take care of edge case when balance fetched is stale, but I think probability of those cases is very low.

**Comment by cryptotavares** [comment]
@jpuri ok yes it makes sense. If the balance is undefined it means that the controller has not been able to fetch it yet (regardless of the reason or the amount of times that it has tried to fetch).
Sooo yes I agree, if it is undefined, then we do not display the warning, but we do not allow the user to confirm the transaction. Are you ok with that behaviour @bschorchit?

(Maybe in a subsequent task we could introduce a warning telling the user that it is taking longer than normal to fetch the account balances.. something like that would improve the user perception of what is going on. Though this seems to be quite an edge case.. not sure if it would ever be prioritised - cc @bschorchit )
