### ISSUE TITLE
[SDK] iOS wallet doesn't direct the user back after connect

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#6582]
**Affected SDKs:**
- iOS Native
- ReactNative
- Unity iOS
- JS Web

**Expected Result:**
After you accept the connection on the wallet you're redirected to the Dapp again

**Actual Result:**
The wallet doesn't send you back to daph

https://images.zenhubusercontent.com/141427485/a11967b2-e7fd-4ad9-89aa-ebbeac406408/screen_recording_2023_06_09_at_18_44_45.mov

**Comment by jpcloureiro** [comment]
Together with @tommasini we implemented this feature natively to replace `react-native-minimizer` dependency

fixed by https://github.com/MetaMask/metamask-mobile/pull/6220/commits/fd84cc56c2d0ff78ec2d668b6b74db06134ef338 & https://github.com/MetaMask/metamask-mobile/pull/6220/commits/c13b69fbb4fc7322cb685c3114e830124951917e

**Comment by christopherferreira9** [comment]
Tested locally on the RN upgrade branch (upgrade/react-native/0.71.6-hermes) and it is solved!
Leaving this issue open as a placeholder for testing in the next RC
