### ISSUE TITLE
[E2E iOS specific] Detox is failing when running tests on bitrise against release builds

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#6610]
Detox on iOS is failing on bitrise. The reason being is because the tests are encountering a fatal error during test execution. See the screenshot of the error below:

![image.png](https://images.zenhubusercontent.com/61030c39db5205425da259ac/9f537251-c8d5-41a5-940c-e48014935733)

You can follow this thread for more info:
<s>https://consensys.slack.com/archives/C04GLB755TK/p1686001534455339?thread_ts=1685635037.860389&cid=C04GLB755TK</s>

**Comment by sethkfman** [comment]
To unblock this issue:
- Need to verify debug detox builds work
- Confirm a TestFlight build and be trigger on a physical device for E2E release testing and passing.

@cortisiko Let chat async on this or reach out.

**Comment by tommasini** [comment]
With the react native upgrade to the version 0.71.6, when changing the configuration of the build on xCode to release.
(To do it, press `cmd+shift+,` )
<img width="450" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/46944231/4ac4de54-562b-412e-aaca-5754b761ae41">

We build and run MetaMask, but after importing or creating a wallet, we have the following errors:
On console, we can detect some errors:
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/3f556189-0066-4c9a-88bb-5e1f5796b8b9)
 
Xcode points to this error
`Unhandled JS Exception: Error: Should not already be working.`

**Comment by tommasini** [comment]
Tried to activate the new architecture on IOS following this [guide](https://reactnative.dev/docs/new-architecture-library-ios):
Upgraded react native to 0-72.rc-6 to support react native reanimated with new architecture:

Having these errors so far:
debug configuration:  index.js: The "id" argument must be of type string. Received undefined
release:  Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions'

**Comment by cortisiko** [comment]
We spoke about this and decided to address the post-RN merge. The temporary solution is to run the E2E tests against a debug build for iOS. Long term solution is to address the crash.

**Comment by tommasini** [comment]
Log progress:
The error is only when navigating to wallet view (from import or create a new wallet, or logging in)
- Commenting wallet/view component or part of it, it would change the error to "Should not already be working"
- Removing react-native-reanimated and Pan gesture handler does not remove the issue
- There was a try to upgrade to new architecture on IOS
- * Never were able to successfully build the app
* Navigating to a different component after login (or other that navigates to wallet) it doesn't crash so it seems the crash it's on the wallet view 

Things to try:
* Wallet view debug
* Remove navigation from login screen (or other that navigates to wallet) 
* Using navigate instead of replace
* Upgrade react navigation

**Comment by tommasini** [comment]
I'm ending the day, what we have found so far:
* Navigation is working 
* The app only crashes if a certain deep of components are rendered

I will explain better the last one here:
Right now I went the deeper possible without a crash, only have commented the lines `131-144`of `onboardingWizard` component, returning a view instead of the onboarding modal, and the line 551 of `Tokens` component (The one that renders the list or the empty text, I let only render the empty text).
Both of this components are rendered on Wallet view.
Uncommenting one of these lines the error is `Unhandled JS Exception: Error: Should not already be working.,`. And it's consistent, it happens when we log in, when we import a wallet or create a new one.

I think this is an error of something on react native or xcode that is not working well yet with the apple chips.

**Comment by tommasini** [comment]
We checked as well the stack size limit of the processor on this apple silicon machine, the difference between the first m1 apple chip (512kb) to an intel processor (8mb), but now the default on the new m1 machines is 8mb as well, and we checked that with the command ulimit -n , It was tried as well to increase the stack size of the simulator itself, hardcoding it on xCode, and the error persists Should not already be working . What tells me is that this is not a stack size issue anymore after commenting described the comment above.

**Comment by tommasini** [comment]
Moving this to the blocked column to discuss new ideas with the team

**Comment by tommasini** [comment]
Next step will try to upgrade react-native without enabling new architecture

**Comment by tommasini** [comment]
Version 0.71.12 -> Same error
Version 0.72.2 -> Stopped with an error `Import of module 'glog.glog.log_severity' appears within namespace 'google'`

On 0.72.2 the only difference on code that we can see on react native upgrade helper, it's on the podfile because we have a custom `react_native_post_install` function and a custom function for the targets, and the config that it's on react native upgrade helper it's on that custom function instead of the parameters of `react_native_post_install`

**Comment by Cal-L** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/6610?planning-poker) with Zenhub @jpcloureiro @MarioAslau @NicolasMassart @tommasini

**Comment by hesterbruikman** [comment]
Workaround exists. 
Expected: E2E should run against release build
Current: E2E runs against debug build on CI

**Comment by tommasini** [comment]
Next move:
* Copy our mobile app code to a new bare bone react native to try to interact after importing wallet/ creating wallet

**Comment by Andepande** [comment]
As discussed with @Cal-L, let's split this ticket into two. Currently facing another [issue](https://app.bitrise.io/build/72a8f17c-f49a-40e7-874a-8ed433b80286) building Android in release mode on Bitrise

**Comment by Andepande** [comment]
with Joao's help I was able to build both IOS and Android, currently blocked by the restore caching issue present on Bitrise

**Comment by cortisiko** [comment]
@Andepande This is excellent news! Can you also run the tests?

**Comment by cortisiko** [comment]
Closing as complete since we now have detox running on QA builds in release mode
