### ISSUE TITLE
walletconect v2 chains not supported

### ISSUE THREAD

**Issue by andriirak** [MetaMask/metamask-mobile#6688]
**Describe the bug**
I have _**Error: Unsupported chains**_. after init @walletconnect/ethereum-provider with **chains** length > 1
` await EthereumProvider.init({
      projectId: walletConnectProjectId,
      walletConnectVersion: 2,
      chains: [Web3Chains.Ethereum, Web3Chains.Goerli]})`

**To Reproduce**
_Steps to reproduce the behavior_
1. call `init `action from @walletconnect/ethereum-provider with `chains: [Web3Chains.Ethereum, Web3Chains.Goerli]` 
2. connect metamask mobile wallet with walletconnect v2
4. See error in console _**Error: Unsupported chains**_

**Expected behavior**
Metamask mobile wallet should be connected without any error

**Smartphone (please complete the following information):**
 - Device: Redmi note 8
 - OS: Android
 - App Version v7.0.1(1126)

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by Raggaer** [comment]
Having the same problem with chains: [137] for Poly

**Comment by kecson** [comment]
Having the same problem with chains: [7001] for ZetaChain Testnet

**Comment by ccosmincc** [comment]
I was facing the same problem and bypassed it by setting my chains as optional. 
```
EthereumProvider.init({
 // other config properties 
 chains: [1], //need to have at least one, so I set mainnet chainId
 optionalChains: [5, 7001] // add here all your chains 
})
```

**Comment by compojoom** [comment]
If you add the chainids to the `optionalChains` you are able to connect, but afterwards you are not able to switch to the defined optional chains.  
Also the error happens when you provide more than one chain in the `chains` prop.
```
EthereumProvider.init({
 // other config properties 
 chains: [1, 5], //need to have at least one, so I set mainnet chainId
 optionalChains: [7001] // add here all your chains 
})
```
And it won't work.

**Comment by anaamolnar** [comment]
Hello, @andriirak. Thanks for reporting! I will pass this on to the team.

**Comment by mostafa-rio** [comment]
Facing the same issue. Fixed it by passing `optionalChains`.
Check out this discussion:
https://github.com/orgs/WalletConnect/discussions/2920

**Comment by andriirak** [comment]
@anaamolnar 
hi, any news, when will it be ready?

**Comment by nexus6nexus6** [comment]
> Facing the same issue. Fixed it by passing `optionalChains`. Check out this discussion: https://github.com/orgs/WalletConnect/discussions/2920

Fixing it with `optionalChains` doesn't really fix it. Problem using that approach is that after you want to switch chains it won't work. Either you'll get an error saying "Error: Failed to switch to chain 'eip155:1'. The chain is not approved or the wallet does not support 'wallet_switchEthereumChain' method"  or you'll just get a positive resolution (`null`) but the chain in the Metamask won't change at all.

@anaamolnar is there any progress on this issue?
Using multiple `chains` just won't let us connect our mobile MM apps with our dapps.
Using `optionalChains` rises other issues..
So we're very much interested into solving this one.

Happens with Metamask Android and iOS apps ver 7.3.0  using latest `"@web3-react/walletconnect-v2": "8.3.7"`

ps: using Metamask browser extension, all works well.

**Comment by meeh0w** [comment]
Any updates on this issue? It's blocking dApps that support multiple chains from fully integrating with Metamask Mobile via Wallet Connect.

**Comment by echovl** [comment]
Having the same problem for 719 (Shiba Inu Testnet)

**Comment by glitch-txs** [comment]
Please update MetaMask to version 7.4.x should be fixed

**Comment by glitch-txs** [comment]
@paro-paro MetaMask only supports one required chain, you need to move the rest to optionalChains

**Comment by paro-paro** [comment]
@glitch-txs thanks!

I understand that the 7.4.x fix was related to the `"Error: Failed to switch to chain 'eip155:1'. The chain is not approved or the wallet does not support 'wallet_switchEthereumChain' method"`

I check it out and it seems to be working fine so sorry for my confusion.

-----

Still, I have found another issue related to the walletconnect + metamask-mobile integration.

Steps to reproduce:

1) Init your ethereum provider with two networks (ETH and CELO)

```
const provider = await EthereumProvider.init({
  projectId: 'foo',
  chains: [1],
  optionalChains: [42220], // celo
  showQrModal: true,
})
```

2) Connect you metamask mobile wallet by scanning the QR code (make sure metamask is connected to Ethereum Mainnet). 

3) Switch to CELO network from the dapp with the `wallet_switchEthereumChain` method. 

```
await provider.request({
   method: 'wallet_switchEthereumChain',
      params: [
        {
          chainId: '0xa4ec',
        },
      ],
    })
```

4) Trigger a `personal_sign` request.

So far, so good. 

Metamask will connect successfully to the dapp (2), the `wallet_switchEthereumChain` will prompt the user to change the network to CELO (3) and the `personal_sign` prompt will also be displayed in the metamask wallet (4).

But, once in this state, if the user...

5) Switches back to ETH network.

In this case, metamask will not prompt the user to change the network but the provider will effectively reflect this change on the `chainChanged` event. I believe this is expected behaviour (changing again to CELO will behave the same way, not prompting the user but reflecting the change in the provider).

6) Triggers again the `personal_sign` request.

Here is when I find the problem: 

Metamask will properly detect that the provider is connected to ETH and before displaying the `personal_sign` prompt, will ask the user to change the network first (since metamask is still connected to CELO).

But after that, it wont sequentially display the sign prompt. The user will have to trigger again the `personal_sign` request (by, for example, clicking the sign message button twice which is unintuitive and feels like the dapp is not working). 

Fortunately, this is the expected behaviour we get if the user switches again to the CELO network and launches the sign request:

=> Metamask will prompt the user for a network change (really nice) and right after that will prompt the sign request (so perfect). 

You can find a reproduction repo [here](https://github.com/paro-paro/poc-wc-mm) in case is useful.

Thanks in advanced.

**Comment by paro-paro** [comment]
Maybe I should open a different issue for this @glitch-txs ?

**Comment by glitch-txs** [comment]
@paro-paro could you post this on a new MetaMask issue? I was actually about to QA this exact flow. Thanks! 🤝

**Comment by paro-paro** [comment]
Great @glitch-txs ! 😄 

Here it is https://github.com/MetaMask/metamask-mobile/issues/7138

Thanks a lot!!

**Comment by andriirak** [comment]
any updates?

**Comment by bonnopc** [comment]
Having a similar issue using WalletConnect V2 + Metamask Android app (`v7.11.0 (1197)`). When I attempt to call the connect method of the provider, I encounter the following error:
```js
{
    "message": "Unsupported chains.",
    "code": 5100
}
```
Here's how I'm currently using it:
```js
const provider = await UniversalProvider.init({
    projectId: WALLETCONNECT_PROJECT_ID,
    metadata: {
        name: "Affine DeFi",
        description: "XXXXX",
        url: "https://XXXXX.com",
        icons: [process.env.APP_LOGO_URL ?? ""],
    },
});
// .....
await provider.connect({
    namespaces: {
        eip155: {
            methods: ["eth_sendTransaction", "eth_signTransaction", "eth_sign", "personal_sign", "eth_signTypedData"],
            chains: ["eip155:1", "eip155:137"],
            // can't use `optionalChains` here as I'm getting the following type error - `'optionalChains' does not exist in type 'Namespace'`
            events: ["chainChanged", "accountsChanged"],
            rpcMap: RPC_URLS,
        },
    },
})
```
Notably, I can successfully connect using the Metamask browser extension and most other wallets using the same approach. Another important thing is I'm using `UniversalProvider` here, not the `EthereumProvider`.

Any insights into this issue would be greatly appreciated! 🙏

**Comment by glitch-txs** [comment]
@bonnopc is highly recommended to use optionalNamespaces for compatibility with smart wallets. https://docs.walletconnect.com/advanced/migration-from-v1.x/namespaces (sorry unrelated topic)

**Comment by icepat** [comment]
Any news on this issue ?
Using optionalNamespaces allows to successfully connect with Metamask but then we don't get prompted to sign the transaction if the network is one of the optionalNamespace's blockchain. 
Rainbow, Trustwallet & others are supporting it without issue.

**Comment by microHoffman** [comment]
this is still an issue @abretonc7s
