### ISSUE TITLE
MM v7.4 crashes consistently after 5 seconds (resolved by deleting and re-installing the app)

### ISSUE THREAD

**Issue by eadonj** [MetaMask/metamask-mobile#6999]
**Describe the bug**
I upgrade to MM 7.4. The app crashed on me after opening, every 5-10 seconds. This happened about 20+ times over the course of 24 hours.

I resolved the issue by deleting the app and reinstalling and reimporting my wallets (not a good experience for an upgrade).

I have an iphone 14 Pro and iOS v16.6

**To Reproduce**
_Steps to reproduce the behavior_
1. Go to MM app 7.4
2. Open the app.
3. Click on any button. Next click will see the screen freeze.
4. Sometimes it crashes and closes and sometimes it just sits there frozen.

**Expected behavior**
App shouldn't crash

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: 16.6
 - App Version [e.g. 1.0.0] - 7.4.0

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by hesterbruikman** [comment]
Hi @eadonj quick questions to better understand when this issue occurs:
- Do you have `App updates` enabled for App store? `Settings `> `App Store`
- Approximately how long had it been since the last time that you opened the app? (Are you a daily, weekly, monthly user?)

Trying to understand whether this is an issue specific to this version or an upgrade gone wrong.
