### ISSUE TITLE
[Bug - SDK] iOS 17 Wallet doesn't send back to dapp

### ISSUE THREAD

**Issue by christopherferreira9** [MetaMask/metamask-mobile#7165]
**Describe the bug**
On iOS 17 (beta as of today) the MetaMask Wallet doesn't send the user back to the dapp as it should.
This seems to be related to Minimmizr. 

**Screenshots**

https://github.com/MetaMask/metamask-mobile/assets/104831203/3600eb87-2cc8-4a31-b320-b745e1b3f71d

**To Reproduce**
1. Connect to any dapp via deeplink
2. See error

**Expected behavior**
The Wallet sends the user back to the dapp after connecting 

**Smartphone (please complete the following information):**

-------------------------------------------------------------
_to be added after bug submission by internal support / PM_
**Severity**

- How critical is the impact of this bug on a user?
- Add stats if available on % of customers impacted
- Is this visible to all users?
- Is this tech debt?

**Comment by xrdavies** [comment]
Are there any updates?

**Comment by codepgq** [comment]
any updates?

**Comment by m1heng** [comment]
any updates? need more attention into this.

**Comment by harry12342** [comment]
any updates?

**Comment by alienzhangyw** [comment]
> Hi all! Unfortunately we are not able to resolve this due to OS limitations on the iOS side. We have implemented a new modal to ask the user to go back to the dapp manually as a workaround. This as been [merged](https://github.com/MetaMask/metamask-mobile/pull/7754) and will be available in the next Mobile Wallet version.

Similar problem here on Android since V7.3.0 and is still no been fixed yet. (#6943)
1. Transaction request on dapp (using wagmi’s useContractWrite) do not call up Metamask, you have to manually switch to Metamask mobile.
2. Metamask do not redirect back to chrome or other Android browsers after signing transactions. Sometimes it only minimize, sometimes nothing happens. You have to manually switch back too.
