### ISSUE TITLE
[Bug]: PPOM - It takes too long to trigger the transaction modal with the feature enabled

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7521]
### Describe the bug

**Problem**: It takes too long to trigger the transaction modal with the feature enabled. My observations with a Malicious ER20 Approval from the [test dapp](https://metamask.github.io/test-dapp/):

1. [Mobile]: With Blockaid enabled: it takes ~ 8 seconds to see the tx modal
2. [Mobile] With Blockaid disabled: it takes ~ <1 second to see the tx modal
3. [Extension] With Blockaid enabled: it takes ~ 1 second to see the tx popup

### Expected behavior

Which should be the threshold here? cc @bschorchit 

### Screenshots

1. [Mobile]: With Blockaid enabled

https://github.com/MetaMask/metamask-mobile/assets/54408225/3154ec2c-a8e1-4880-8bf2-32e56c408af5

2. [Mobile]: With Blockaid disabled:

https://github.com/MetaMask/metamask-mobile/assets/54408225/4e4d36a4-35d4-4c77-9dce-819964d721e0

3. [Extension] With Blockaid enabled

https://github.com/MetaMask/metamask-mobile/assets/54408225/3439f626-0a34-4a56-b26a-0723297c1196

### Steps to reproduce

1. Select Mainnet
2. Enable Blockaid
3. Go to the test dapp
4. Click Malicious Approval

### Version

Integrate PPOM branch  (behind feature flag) https://github.com/MetaMask/metamask-mobile/pull/7363

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
I also noticed this delay:

Without blockaid:
https://github.com/MetaMask/metamask-mobile/assets/2182307/87163f3d-c0c1-42b6-a064-c346a0648dbb

With blockaid:
https://github.com/MetaMask/metamask-mobile/assets/2182307/23034660-5039-4f41-ac87-44b80c18d460

**Comment by jpuri** [comment]
I looked deeper into the performance of blockaid validation for mobile and I got some useful findings:

Time for first confirmation:
1. Time spend in loading wasm - 84ms
2. Time spent in downloading / reading files - 5675ms
3. Time taken to validate the request by wasm code - 3870ms
Total time taken was ~9631ms

Time taken for subsequent confirmation requests on same network:
1. Time spend in loading wasm - 0ms
2. Time spent in downloading / reading files - 0ms
3. Time taken to validate the request by wasm code - 2519ms
Total time taken was ~2520ms

We can improve at point-1,2 above.
1. Loading wasm - we should do it as soon as PPOMController is constructed so that it is not done during confirmation request (current we do this when we receive the first confirmation request)
2. Loading files into wasm can also be optimised, we should do it once all files for the network are fetched by background scheduled job and not delay this to time when first confirmation request is received. Also, this PR by @olu https://github.com/MetaMask/ppom-validator/pull/56 will help in reading file from storage in mobile as it introduces use of controller storage for files.

Point-2 may still remain a delay in situations when all files for the network could not be fetched in advance when confirmation request is received. Also, this will be issue when MetaMask extends multi-network support and send requests for multiple networks at same time.

Point - 3 is time taken by wasm code in verifying the request and it appears that this is wasm also takes more time for first confirmation. We can check with blockaid team to possibly optimise this further.

**Comment by jpuri** [comment]
I looked deeper into the performance of blockaid validation for mobile and I got some useful findings:

Time for first confirmation:
1. Time spend in loading wasm - 84ms
2. Time spent in downloading / reading files - 5675ms
3. Time taken to validate the request by wasm code - 3870ms
Total time taken was ~9631ms

Time taken for subsequent confirmation requests on same network:
1. Time spend in loading wasm - 0ms
2. Time spent in downloading / reading files - 0ms
3. Time taken to validate the request by wasm code - 2519ms
Total time taken was ~2520ms

We can improve at point-1,2 above.
1. Loading wasm - we should do it as soon as PPOMController is constructed so that it is not done during confirmation request (current we do this when we receive the first confirmation request)
2. Loading files into wasm can also be optimised, we should do it once all files for the network are fetched by background scheduled job and not delay this to time when first confirmation request is received. Also, this PR by @olu https://github.com/MetaMask/ppom-validator/pull/56 will help in reading file from storage in mobile as it introduces use of controller storage for files.

Point-2 may still remain a delay in situations when all files for the network could not be fetched in advance when confirmation request is received. Also, this will be issue when MetaMask extends multi-network support and send requests for multiple networks at same time.

Point - 3 is time taken by wasm code in verifying the request and it appears that this is wasm also takes more time for first confirmation. We can check with blockaid team to possibly optimise this further.

**Comment by jpuri** [comment]
@bschorchit : we can plan tasks to address above findings.

**Comment by hilvmason** [comment]
@jpuri will break these down into 2 tasks and have both added to this sprint (Oct 23 start)

**Comment by jpuri** [comment]
I created following issues:

https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-planning/1554 

https://app.zenhub.com/workspaces/-confirmations-secure-ux-6245e6e2348677001213b8d2/issues/gh/metamask/metamask-planning/1555

**Comment by hilvmason** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/7521?planning-poker) with Zenhub @blackdevelopa @digiwand @jpuri @seaona @segun

**Comment by jpuri** [comment]
@bschorchit , @seaona : we are working on mobile performance optimisations, I am hoping to get good improvements in performance, but there still might be edge cases that will be slow. For instance if user enables Blockaid and immediately submits a transaction and gives no time to prefetch data files - in this scenario we will have to instantly fetch all data files some of which are huge and this can cause delay in mobile platform. Apparently it seems extension is still good.

What is making performance bit challenging for blockaid is that data files are huge, fetching them takes long and also keeping them in memory is expensive.

I think we should do a UX improvement in mobile, currently we intervene incoming transaction for validation. But approach we can take is show incoming transaction on UI, but in background validate it, till validation is in progress we can show spinner and as soon as validation is completed we show warning. This approach will take care of all edge cases. I expect this to be about 5 seconds delay on confirmation page for the edge cases.

cc @segun , @cryptotavares

**Comment by jpuri** [comment]
I tested mobile with performance optimisations:

Time on very first transaction immediately after enabling PPOM: ~8000 ms
Any subsequent transaction on same chain: ~1500 ms

**Comment by jpuri** [comment]
@bschorchit , @SayaGT : I am blockaid for designs to complete this. Can you please help.

**Comment by SayaGT** [comment]
Hey @jpuri you can use the skeleton loaders for the content thats taking longer. Here is [my static design](https://www.figma.com/file/7kYok9B46ohR6h47cksRAz/Confirmation-redesign-V1?type=design&node-id=907%3A26372&mode=design&t=mqfoqFJtVIZo9Txg-1) to show the skeleton loaders. Also [here is a reference for skeleton loader in Material UI](https://mui.com/material-ui/react-skeleton/).

We should have these on component level to make the experience better. CC: @georgewrmarshall

**Comment by bschorchit** [comment]
@SayaGT to confirm understanding is the design proposal to have this skeleton on the warning component level only, right?

**Comment by SayaGT** [comment]
Yes, my design just shows the worst case scenario of nothing loads but the proposal is to have the loader on component level to have the best UX possible.

**Comment by jpuri** [comment]
Hey @SayaGT : the designs look harder on react native. On react native we have loaders like these available: https://reactnative.dev/docs/activityindicator

Additionally we should I think show loading indicator only in blockaid validation banner and add some text like **validation in progress**.

Also, as I remember from our discussion we will not block confirm button for validation result to load.
