### ISSUE TITLE
[Bug]: Swap is not working after the onboarding step

### ISSUE THREAD

**Issue by davibroc** [MetaMask/metamask-mobile#7634]
### Describe the bug

After the pass the swap onboarding the swap page doesn't appear and swap become unavailable

Watch the video:

https://github.com/MetaMask/metamask-mobile/assets/6082863/bb7b50fa-4aef-4576-9e00-aa6f45e615f3

### Expected behavior

After I pass the onboarding step I am able to swap

### Steps to reproduce

1. After installing the app click on the action menu
2. Select Swap
3. Click on Start Swapping
4. Notice that the Swap page doesn't appear and Swap becames disabled from action menu

### Version

7.9.0

### Build type

None

### Device

iPhone 12 Pro Simulator

### Operating system

iOS

**Comment by chrisleewilcox** [comment]
@davibroc I wasn't able to reproduce on my physical iPhone 12.  I also tested against 7.10.0 and wasn't able to reproduce.  I will try on simulator.

**Comment by wachunei** [comment]
This is expected in the case Swaps API indicates the network is deactivated or API is down or unreachable (blocked at a DNS or network level).

[Here's the code that runs that check](https://github.com/MetaMask/metamask-mobile/blob/3022144b736727b8f15536d90a067087f85860ed/app/components/UI/Swaps/index.js#L252-L302), it updates the liveness state so the button is not visible anymore (in previous versions the button was disabled instead of hidden)

**Comment by dan437** [comment]
Hi, there was a change in a dev URL about a month ago: https://github.com/MetaMask/swaps-controller/blame/main/src/constants.ts#L30

Feature flags were off for mobile. After turning them on it works.
