### ISSUE TITLE
[Bug]: ERC20 Approve with a huge amount suggested by the dapp, changes the amount in the Approve Screen

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-mobile#7671]
### Describe the bug

**Problem**: whenever we are suggesting a huge amount to Approve an ERC20 from a dapp, we can see how the approve value on the Confirmations screen is different.

### Expected behavior

The value should not be changed. See Extension

![Screenshot from 2023-11-02 19-43-20](https://github.com/MetaMask/metamask-mobile/assets/54408225/21d838ac-8f83-4fd0-876d-24c280c617d1)

### Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/376d36f1-a772-454b-ba11-2e9828c2580e

### Steps to reproduce

1. Select Goerli network
2. Go to this contract https://goerli.etherscan.io/address/0x286358eec6af1386b4365bfd91fb8a323b5282dc#writeContract
3. Mint some tokens
4. Click Approve
5. Add any recipient and this token amount `222222222222222222222222222222222222222222`
6. Click Write
7. See Confirmations screen displays another value: `222222222222222240793630.867943122305810432`

### Version

7.9.0 production

### Build type

None

### Device

Pixel 6

### Operating system

Android

**Comment by jpuri** [comment]
This issue seems to be fixed already in latest code:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3868c4b7f3a1ebca2464f8de49f8872924644efc/Screenshot%202024-04-23%20at%205.06.13%E2%80%AFPM.png" alt="Screenshot 2024-04-23 at 5.06.13 PM.png" />
