### ISSUE TITLE
MetaMask Mobile SDK - App crashes shortly after opening

### ISSUE THREAD

**Issue by SudipVdoit** [MetaMask/metamask-mobile#7752]
### What is this about?

I've been working with the MetaMask Mobile SDK and followed the instructions outlined in the README (link to the README here: https://github.com/MetaMask/metamask-mobile/tree/develop) to generate an APK. However, I'm facing an issue where the app crashes after 1 or 2 seconds of being opened.

Despite careful implementation and a thorough review, I haven't encountered any specific error messages or code snippets that might help us pinpoint the cause of the crash. I have conducted these steps on Ubuntu 22.04.

I'm also curious to know whether others have successfully generated an APK from this GitHub repository already? If so, could you please share any insights or additional steps that might be necessary for a successful build?

https://github.com/MetaMask/metamask-mobile/assets/127386852/f812f2c0-fa0b-4f1d-8ed3-0b9004e41787

**Comment by anaamolnar** [comment]
Hello @SudipVdoit. Thanks for reporting! I will pass this on to the SDK team. They will provide an update on this as soon as they can.

**Comment by A-Feder** [comment]
Hi @SudipVdoit , for completeness, I am including the info from your other ticket as well:

**Environment Info:**
The issue is occurring in a development environment using Ubuntu 22.04. We are utilizing the MetaMask Mobile SDK and following the instructions outlined in the README (link to the README: https://github.com/MetaMask/metamask-mobile) to generate an APK. The app crashes after 1 or 2 seconds of being opened, and despite our careful implementation and review, we have not identified specific error messages or code snippets to pinpoint the cause of the crash. Additionally,
the build process involves Gradle version 6.9. node js version: 14.15.0, java version: 11.0.20, buildToolsVersion = "30.0.3", minSdkVersion = 23, compileSdkVersion = 31, targetSdkVersion = 30, kotlin_version = "1.6.0".

**MetaMask SDK Version:** 
4.0.0 ,cloned from github repo :https://github.com/MetaMask/metamask-mobile/tree/develop

**MetaMask App Version:** 
4.0.0 , Android (check attachment)

**Deployment Method:** 
I deploy my application by generating an APK using the MetaMask Mobile SDK. I closely followed the instructions provided in the README (link: https://github.com/MetaMask/metamask-mobile) for the deployment process.

**Bug Description:** 
After generating the APK using the MetaMask Mobile SDK following the instructions provided in the README, the app consistently crashes within 1-2 seconds of being opened

**Expected Behaviour:** 
Upon installing the APK and clicking to open, I expected MetaMask Mobile to open the wallet setup mobile screen
Link to GH Repository: https://github.com/MetaMask/metamask-mobile/tree/develop

**Steps to Reproduce:** 
I followed the instructions outlined in the README file of the MetaMask repository, specifically located at the provided link. Despite adhering to the provided guidelines, the issue persists as described in the bug description.

**Screenshots and Logs:** 
No logs were generated. See video in the opening post.

![appVersion](https://github.com/MetaMask/metamask-mobile/assets/118213963/cd49598c-586e-4ab0-96a8-9e0a69c0ac5e)
![sdkVersion](https://github.com/MetaMask/metamask-mobile/assets/118213963/40752703-1ff3-4d37-98e0-612183d29b26)

**Comment by A-Feder** [comment]
@SudipVdoit please, while we review this issue, make sure to update MetaMask and the SDK to their latest versions where possible

**Comment by SudipVdoit** [comment]
@A-Feder, the app I've installed is generated from the following branch: https://github.com/MetaMask/metamask-mobile/tree/develop
I've attempted to generate and install the app using the commands yarn start:android and ./gradlew assembleRelease. Unfortunately, the result remains the same—the app crashes.

Could you please provide step-by-step instructions on how to update both MetaMask App and SDK to their latest versions? Your guidance would be greatly appreciated.

**Comment by SudipVdoit** [comment]
App crashing issue is resolved after updating to version 7.10.0, thanks
