### ISSUE TITLE
[Bug]: Missing Translation for Biometric Authentication Feature in Canadian English Localization

### ISSUE THREAD

**Issue by rmashate** [MetaMask/metamask-mobile#7941]
### Describe the bug

Users with the Canadian English (en-CA) locale experience a missing translation error when attempting to enable biometric authentication in the application. The error message displayed is "[missing "en-CA.biometrics.enable_fac translation]".

### Expected behavior

The application should display a Canadian English translation for enabling biometric authentication, allowing the user to unlock the wallet using facial recognition.

### Screenshots/Recordings

![Screenshot_20231128-210515](https://github.com/MetaMask/metamask-mobile/assets/5077049/329faee2-5628-4c9a-87a0-d87788f22a05)

### Steps to reproduce

Open the application.
Navigate to the login screen.
Observe the error message in the biometric authentication section.

### Error messages or log output

```shell
missing "en-CA.biometrics.enable_face translation
```

### Version

7.11

### Build type

None

### Device

Google Pixel 4 

### Operating system

Android

### Additional context

Ensure that all language keys are correctly implemented in the application's i18n (internationalization) files.
Add a missing translation string for "en-CA.biometrics.enable_fac" in the relevant localization file.

**Comment by anaamolnar** [comment]
Hello, @rmashate. Thanks for reporting! I will pass this on to the team.

**Comment by gauthierpetetin** [comment]
Even if translation is missing, it shall fallback to english.

**Comment by NicolasMassart** [comment]
I tested it and was not able to reproduce with what we currently have on main:
![image](https://github.com/MetaMask/metamask-mobile/assets/4677568/ae186b0d-c17f-43fb-9744-982b05ec3d52)
![image](https://github.com/MetaMask/metamask-mobile/assets/4677568/da4e3d2b-d22b-4233-9b7e-97b31c31db52)

However, the only way to reproduce is to actually remove the string from the en.json file so that it's not available for any english variant and then it will display the error when your language is Canadian English (en-CA)
![image](https://github.com/MetaMask/metamask-mobile/assets/4677568/8e81cd62-56ea-47e6-b8bb-a5c3a1de6ae4)

But this string has been in the en.json since [848daebbeb40d97683ea9dbc4018af92581c518f](https://github.com/MetaMask/metamask-mobile/commit/848daebbeb40d97683ea9dbc4018af92581c518f#diff-c9218bed23f0aeb93d7e1a7d5f6e1345fae20f4b8692b27fb97fd0f37b3d26d7R352) (2018) so I see no reason for it to suddenly fail on version 7.11 as reported in the issue.
Unless the RN translation system is completely broken or something else made it fail, I don't see any reason to worry. It works as expected.
I also confirm the fallback to english works, I removed the string from the french file and text is properly displayed in english by default:
![image](https://github.com/MetaMask/metamask-mobile/assets/4677568/e4e2122f-b7b5-46b3-9b8d-741ff10a769e)

**Comment by gauthierpetetin** [comment]
Thanks a lot for the investigation @NicolasMassart!
