### ISSUE TITLE
[Bug] Tapping on a dapp deep link and mobile app is not launched, only the mobile app is launch but not redirected to the dapp in the browser

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#8398]
Given I have a universal deep link and metamask mobile is not in the background, when I tap on the deep link, then metamask mobile should launch, but the dapp is not opened on the in build browser. 

### Acceptance Criteria

The page will reload and show researchers content
The address bar should still be the researchers url and not update
This site will navigate to www.microsoft.com after some time

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by UnfortuN8** [comment]
related to: https://github.com/MetaMask/metamask-mobile/issues/8388

**Comment by christopherferreira9** [comment]
Fixed by https://github.com/MetaMask/metamask-mobile/pull/8469 | Not related to https://github.com/MetaMask/metamask-mobile/issues/7928

iOS:

https://github.com/MetaMask/metamask-mobile/assets/104831203/47f42ba5-7041-434e-bf5a-1c939ea85d7f

Android:

https://github.com/MetaMask/metamask-mobile/assets/104831203/bfff3023-f50d-4d02-89d8-62edf190011b
