### ISSUE TITLE
[Bug]: not able to purchase ticket with wallet on dapp using moongate

### ISSUE THREAD

**Issue by chrisleewilcox** [MetaMask/metamask-mobile#8462]
### Describe the bug

7.15.0
Android
SDK (*I think)
This was using Moongate to buy a ticket. Below my attempt at generalized steps to reproduce:

- Open dapp in native browser (Firefox) https://app.moongate.id/e/eth-dam
- Tap Connect account
- Get prompt in Metamask to connect
- Connect and continue in dapp
- Tap pay
- Deeplink payment request to MetaMask
- Error is shown
- App did not crash. I could close the error message and continue manually

Issue has been reported in production with ca [11 reports across Mobile & Extension](https://consensys.zendesk.com/agent/search/1?copy&type=ticket&q=%22there%20are%20keyrings%2C%20but%20none%20match%20the%20address%22) since Jan 2023

Ping @anaamolnar or @hesterbruikman for access to more details when investigating

### Expected behavior

Should be able to purchase on dapp that uses moongate with crypto on mobile wallet.

### Screenshots/Recordings

https://consensys.slack.com/files/U051LN5QMBN/F06FYNC5WR4/screenshot_20240127-120600_metamask.jpg
https://consensys.slack.com/files/U051LN5QMBN/F06G7R4T2MA/screenshot_20240127-120543_metamask.jpg

### Steps to reproduce

```
Open dapp in native browser (Firefox)
Tap Connect account
Get prompt in Metamask to connect
Connect and continue in dapp
Tap pay
Deeplink payment request to MetaMask
Error is shown
App did not crash. I could close the error message and continue manually
```

### Error messages or log output

```shell
https://consensys.slack.com/files/U051LN5QMBN/F06FYRC35SA/125813384905010.txt
```

### Version

7.15.0
First seen on - Mobile - 5.12.3 (see [Liveperson](https://consensys.zendesk.com/agent/search/1?copy&type=ticket&q=%22there%20are%20keyrings%2C%20but%20none%20match%20the%20address%22))

### Build type

None

### Device

Samsung

### Operating system

Android

**Comment by gantunesr** [comment]
@hesterbruikman which address were you using?

**Comment by seaona** [comment]
I've just encountered a similar error in main and I confirm I encountered the exact same thing a couple of weeks ago (I didn't open an issue because I thought it was something around my setup and couldn't repro again):

1. I had the wallet working yesterday and I believe I left it open
2. The phone has auto-lock screen, so today the phone was locked
3. I've unlocked the phone, and I encountered the MetaMask screen No internet connection I refreshed and I was already logged in - I didn't have to add a password
4. I went to the browser and the test-dapp was already open - I was expecting to be already connected, since I was yesterday, but it appeared as I was not connected
5. I clicked the Connect button again and I see there is no Account in the Connect Account Modal
6. I Confirm and I see the error `The address is not imported`
7. When I try to add an account I see the error ` No HD Keyring found`
8. When I try to send a transaction I see the error `KeyringController - Cannot persist vault without password and encryption key`


https://github.com/MetaMask/metamask-mobile/assets/54408225/86fefdbf-282a-49ee-8928-a51218eba243


https://github.com/MetaMask/metamask-mobile/assets/54408225/516e651a-30d6-4510-bbd7-be5ab062603e

**Comment by seaona** [comment]
For the one who fixes it, I can confirm that:
- it happens every time my phone screen is locked
- and when I unlock it, if I get into the You're offline screen (it does not always happen)
- and when I re-try it, I don't have to unlock the wallet - I land already in the Home screen

![Screenshot from 2024-01-31 14-42-28](https://github.com/MetaMask/metamask-mobile/assets/54408225/10f5e778-e46c-481f-ab01-39c263a47ce7)

https://github.com/MetaMask/metamask-mobile/assets/54408225/c5427ccc-3e4e-4d31-99ff-d705943006a7
