### ISSUE TITLE
How to submit a Dapp to your home page? 

### ISSUE THREAD

**Issue by rstormsf** [MetaMask/metamask-mobile#928]
I have a few popular Dapps:
1. https://multisender.app ( 10k txs on mainnet, works on kovan, ropsten, rinkeby, gorli, poa, xdai)
2. https://erc20faucet.com - 1,000 daily visitors, supports all major testnets

**Comment by brunobar79** [comment]
Just so you are aware during the Beta our main focus will be fixing bugs and iterating new features prior to V1 launch. But we will be making changes and adding to our featured DApps sections as well. If you can please fill out this intake form in order to help us understand your DApp and position better:  https://docs.google.com/forms/d/e/1FAIpQLSenMkF-3n3W83j3DJrqGfKHoY-B6WcbkmHT4jWNYNuYjxQQYQ/viewform

**Comment by eason1305** [comment]
@brunobar79 Hi, I'm Eason from C.R.E.A.M. Finance team.

I'm wondering whether the Google Form link above is still open for DApp submission. If not, please tell me where I can submit our DApp, for that link seems the only way to submit DApp to your mobile browser. Thanks.
